Gather

In [32]:
# Importing the required libraries :
import pandas as pd
import numpy as np
import requests
import os
import tweepy
import time
import json
import re
import itertools
import time
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Gather File -> twitter-archive-enchanced.csv

In [33]:
# Read the twitter_archive_enhanced.csv file which is stored in the porject folder
twitter_archive = pd.read_csv("twitter-archive-enhanced.csv", sep="," )
twitter_archive.head(2)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643555336193/photo/1,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV",NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421306343426/photo/1,13,10,Tilly,None,None,None,None

Gather file -> image-predictions.tsv using url

In [34]:
# Download tweet image predictions provided by Udacity
tweet_image_prediction_url = "https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"
response = requests.get(tweet_image_prediction_url)

In [35]:
# Save the image-predictions.tsv locally:
with open(os.path.join(os.getcwd(), 
         tweet_image_prediction_url.split('/')[-1]), mode='wb') as file:
    file.write(response.content)

In [36]:
# Import the predictions into DataFrame
image_predictions = pd.read_csv("image-predictions.tsv", sep="\t" )

Gather tweets data from Twitter API

In [37]:
#Fetch the tweets from the Twitter API
# authentication keys
consumer_key = 'eL2DeeOX1wX7HH0Ldu3Jy6qNT'
consumer_secret = '0QnVbYfZlYxzuJI4Mx9GDIEb8uiQJlLoMBCyDH4V1KvxeCt6tF'
access_token = '852228407140261893-0sCUBrO7a2lnroq6sFhcRqCnn3QdPsS'
access_secret = 'qcHOxjOfFmrBaTkNp0rFJLLCtfL0hSR2ytQGOWlUo05Zj'

In [38]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
#Create the list of ids for fetching the tweets
#Use the ids of twitter_archive DataFrame
list_of_ids_in_twittter_archive = twitter_archive['tweet_id'].tolist()

In [40]:
# Fetch all tweets from the twitter API using loop:
list_of_tweets = []
# Tweets which are not useful are saved in a list 
cant_find_tweets_for_those_ids = []
for each_id in list_of_ids_in_twittter_archive:   
    try:
        start = time.time()
        list_of_tweets.append(api.get_status(each_id))
        end = time.time()
        print(end - start)
    except Exception as e:
        cant_find_tweets_for_those_ids.append(each_id)
        print(str(each_id))

0.1779334545135498
0.16844606399536133
0.16751360893249512
0.19694185256958008
0.20322656631469727
0.17343401908874512
0.16757416725158691
0.2596127986907959
0.18889117240905762
0.17571330070495605
0.1694016456604004
0.17273640632629395
0.16713881492614746
0.19635581970214844
0.1742544174194336
0.1765298843383789
0.16849541664123535
0.18430590629577637
0.16853046417236328
888202515573088257
0.18601250648498535
0.17920279502868652
0.2063584327697754
0.17048072814941406
0.17329025268554688
0.1917107105255127
0.17514538764953613
0.22866320610046387
0.16923236846923828
0.17304348945617676
0.21948742866516113
0.17502999305725098
0.19035053253173828
0.18187570571899414
0.1863095760345459
0.18194866180419922
0.1779797077178955
0.1752760410308838
0.1976175308227539
0.16774821281433105
0.17686867713928223
0.17339301109313965
0.3808598518371582
0.2082526683807373
0.16738104820251465
0.20182538032531738
0.1695418357849121
0.18388652801513672
0.1800534725189209
0.22054314613342285
0.1748027801513672
0.18349385261535645
0.17667889595031738
0.17508935928344727
0.17804694175720215
0.18478035926818848
0.17504644393920898
0.17015862464904785
0.17092251777648926
0.16876697540283203
0.1872544288635254
0.17394495010375977
0.2785532474517822
0.16948556900024414
0.1795511245727539
0.1944737434387207
0.17054486274719238
0.1656200885772705
0.18986272811889648
0.16357684135437012
0.1822512149810791
0.18117094039916992
0.2043445110321045
0.17191171646118164
0.17346930503845215
0.17087054252624512
0.1836857795715332
0.17999267578125
0.2110762596130371
0.16763949394226074
0.22075128555297852
0.1727278232574463
0.1834266185760498
0.18347811698913574
0.16664838790893555
0.1947638988494873
0.18016910552978516
0.2687699794769287
0.18012380599975586
0.18199920654296875
0.18998050689697266
0.23620820045471191
0.16940808296203613
0.17313075065612793
0.18438982963562012
873697596434513921
0.17612767219543457
0.18397212028503418
0.18570566177368164
0.17741012573242188
0.20960307121276855
872668790621863937
0.17365336418151855
0.18114924430847168
0.20687389373779297
0.1677231788635254
0.1735682487487793
0.16350984573364258
0.17018675804138184
0.18265342712402344
0.17711758613586426
0.16804003715515137
0.1772005558013916
0.17284488677978516
0.19585084915161133
0.177931547164917
0.169586181640625
0.16812419891357422
869988702071779329
0.1672661304473877
0.16969943046569824
0.19334936141967773
0.16589975357055664
0.20787763595581055
0.1715712547302246
0.16501474380493164
0.17947053909301758
0.18589043617248535
0.16193079948425293
0.17327451705932617
0.25107860565185547
0.18387126922607422
866816280283807744
0.17829394340515137
0.17428827285766602
0.22041082382202148
0.17543673515319824
0.1810894012451172
0.17692255973815918
0.19368410110473633
0.1741931438446045
0.17505192756652832
0.16790437698364258
0.18751788139343262
0.18873953819274902
0.1777019500732422
0.17958593368530273
0.16841363906860352
0.18677163124084473
0.16934800148010254
0.17313647270202637
0.16713666915893555
0.25376296043395996
0.19605374336242676
0.1745152473449707
861769973181624320
0.2054455280303955
0.17186927795410156
0.19187331199645996
0.17844486236572266
0.18532848358154297
0.16753244400024414
0.18082833290100098
0.17086291313171387
0.16935944557189941
0.18466854095458984
0.18198490142822266
0.16783428192138672
0.1697218418121338
0.17078495025634766
0.16761040687561035
0.18948841094970703
0.16631746292114258
0.16939687728881836
0.18218779563903809
0.19016146659851074
0.20323991775512695
0.1838700771331787
0.16826295852661133
0.1677722930908203
0.190535306930542
0.1714320182800293
0.17318153381347656
0.16496014595031738
0.18578243255615234
0.19048070907592773
0.17510008811950684
0.18118953704833984
0.264240026473999
0.1761465072631836
0.186842679977417
0.18743085861206055
0.18128466606140137
0.25347113609313965
0.18845295906066895
0.19177889823913574
0.21123552322387695
0.17754173278808594
0.1725766658782959
0.17774105072021484
0.16736555099487305
0.1736469268798828
0.19502806663513184
0.20598149299621582
0.17456436157226562
0.1683661937713623
0.19359683990478516
0.1655869483947754
0.1740260124206543
0.1838853359222412
0.17564940452575684
0.1904919147491455
0.1707913875579834
0.17276906967163086
0.17329192161560059
0.8480479717254639
0.17601418495178223
0.18185067176818848
0.1695864200592041
0.1694338321685791
0.19138479232788086
0.1857287883758545
0.17461490631103516
0.17093992233276367
0.17754149436950684
0.17758822441101074
0.19424700736999512
0.16775870323181152
0.1699047088623047
0.17998528480529785
0.17093467712402344
0.1717071533203125
0.1648414134979248
0.17814302444458008
0.1692945957183838
0.16814470291137695
0.17795157432556152
0.1752617359161377
0.17734551429748535
0.17211055755615234
0.2293086051940918
0.21490097045898438
0.28324103355407715
0.1822507381439209
0.17093157768249512
0.17136740684509277
0.20059847831726074
845459076796616705
0.229386568069458
0.17346835136413574
0.1740255355834961
0.20781350135803223
0.17225122451782227
0.17151212692260742
0.16959142684936523
0.2362842559814453
0.17043018341064453
0.16931438446044922
0.19075512886047363
0.17599940299987793
842892208864923648
0.1702110767364502
0.18721461296081543
0.19260096549987793
0.1701347827911377
0.22873830795288086
0.17415189743041992
0.18656539916992188
0.16886377334594727
0.18936824798583984
0.17459940910339355
0.18048858642578125
0.17499542236328125
0.18390798568725586
0.1731419563293457
0.17516160011291504
0.2057178020477295
0.18191266059875488
0.22618770599365234
0.16886281967163086
0.17469072341918945
0.17097806930541992
0.18272924423217773
0.18526101112365723
0.17544150352478027
0.1840834617614746
0.18696141242980957
0.17236614227294922
0.17493200302124023
0.17655730247497559
0.19003701210021973
0.19492077827453613
0.17080307006835938
0.1746225357055664
0.21884775161743164
0.1830451488494873
0.17229866981506348
0.16968798637390137
837012587749474308
0.16944003105163574
0.1771390438079834
0.17427921295166016
0.17479729652404785
0.19849181175231934
0.18884515762329102
0.17113280296325684
0.18370366096496582
0.18970894813537598
0.1692342758178711
0.19373559951782227
0.17304611206054688
0.18768715858459473
0.17878961563110352
0.19007086753845215
0.18503952026367188
0.20992660522460938
0.2073380947113037
0.16949152946472168
0.178330659866333
0.18698883056640625
0.1912398338317871
0.17798161506652832
0.16961073875427246
0.17532634735107422
0.20060396194458008
0.19023776054382324
0.18857359886169434
0.18074321746826172
0.1698610782623291
0.17891669273376465
0.16724061965942383
0.17031407356262207
0.1728529930114746
0.1806941032409668
0.1878199577331543
0.17242980003356934
0.16898155212402344
0.1843574047088623
0.17041707038879395
0.17633414268493652
0.19061040878295898
0.17831206321716309
0.17331576347351074
0.1745011806488037
Rate limit reached. Sleeping for: 84
89.26564407348633
0.21805882453918457
0.17193222045898438
0.1784508228302002
0.17901825904846191
0.19454741477966309
0.19153809547424316
0.18163347244262695
0.17998623847961426
0.1782853603363037
0.16559863090515137
0.19011569023132324
0.16961908340454102
0.16951441764831543
0.16872191429138184
0.22884202003479004
0.1854724884033203
0.17070460319519043
0.17154765129089355
0.1795816421508789
0.1699223518371582
0.17788314819335938
0.18281078338623047
0.1786329746246338
0.179368257522583
0.186509370803833
0.19437384605407715
0.18184232711791992
0.16913390159606934
0.17017126083374023
0.17637372016906738
0.16444683074951172
0.18320083618164062
0.16682863235473633
0.16935396194458008
0.1675715446472168
0.17452692985534668
0.1845085620880127
827228250799742977
0.4456202983856201
0.36869001388549805
0.16711854934692383
0.18498706817626953
0.1716458797454834
0.16708970069885254
0.1652538776397705
0.20074081420898438
0.16728615760803223
0.17620372772216797
0.17344331741333008
0.18069815635681152
0.17795801162719727
0.17100882530212402
0.17408442497253418
0.21236467361450195
0.17802023887634277
0.17437243461608887
0.1777501106262207
0.19212794303894043
0.16962647438049316
0.1824054718017578
0.1936044692993164
0.19814205169677734
0.17284464836120605
0.18013715744018555
0.1787712574005127
0.19761085510253906
0.17187166213989258
0.17187976837158203
0.36614227294921875
0.18042731285095215

0.18380260467529297
0.17403769493103027
0.17730379104614258
0.200056791305542
0.17263126373291016
0.18114089965820312
0.1742556095123291
0.18198156356811523
0.17203307151794434
0.16775298118591309
0.3110170364379883
0.18653154373168945
0.17285895347595215
0.17265939712524414
0.17423534393310547
0.19347763061523438
0.1910548210144043
0.16882586479187012
0.17151713371276855
0.18851375579833984
0.17737579345703125
0.218977689743042
0.16531610488891602
0.18863868713378906
0.16982007026672363
0.18106937408447266
0.18790030479431152
0.1863999366760254
0.1729443073272705
0.16898059844970703
0.16697978973388672
0.2533571720123291
0.22549080848693848
0.18222308158874512
0.1776731014251709
0.17853331565856934
0.16871213912963867
0.17314743995666504
0.20482921600341797
0.16776466369628906
0.18249869346618652
0.16656017303466797
0.18903112411499023
0.19241952896118164
0.17065024375915527
0.17784452438354492
0.18341660499572754
0.1769087314605713
0.1729717254638672
0.16959261894226074
0.18833541870117188
0.17711639404296875
0.16675305366516113
0.1673569679260254
0.1938343048095703
0.17201471328735352
0.1714789867401123
0.17151665687561035
0.18585205078125
0.1901099681854248
0.1721487045288086
0.19176721572875977
0.18723654747009277
0.16974115371704102
0.18017983436584473
0.16550183296203613
0.18958425521850586
0.17404913902282715
0.1742410659790039
0.17629551887512207
0.1873631477355957
0.18462777137756348
0.1705467700958252
0.17845869064331055
0.19798827171325684
0.17400074005126953
0.21535086631774902
0.17897868156433105
0.22395944595336914
0.16985726356506348
0.17019271850585938
0.17346978187561035
0.18679428100585938
0.17046856880187988
0.17075085639953613
0.20546913146972656
0.1854569911956787
0.1770787239074707
0.1782686710357666
0.16544532775878906
0.1855030059814453
0.17860817909240723
0.1672229766845703
0.1718132495880127
0.20069336891174316
0.18170690536499023
0.18442606925964355
0.17186880111694336
0.1796112060546875
0.17200374603271484
0.20569396018981934
0.17168474197387695
0.18562793731689453
0.17967462539672852
0.17073845863342285
0.18244457244873047
0.1704425811767578
0.1923658847808838
0.18368887901306152
0.18152427673339844
0.16775178909301758
0.1770462989807129
0.17055559158325195
0.1682448387145996
0.17282390594482422
0.1804347038269043
0.17103171348571777
0.17629528045654297
0.17190289497375488
0.18264436721801758
0.22546052932739258
0.1756124496459961
0.1905059814453125
0.18899750709533691
0.20304465293884277
0.16553544998168945
0.18503761291503906
0.23005414009094238
0.1737983226776123
0.1730649471282959
0.1728067398071289
0.19401073455810547
0.17340803146362305
0.18988752365112305
0.19780278205871582
0.1950058937072754
0.1775655746459961
0.18157124519348145
0.17021703720092773
0.2164320945739746
0.2052905559539795
0.1715996265411377
0.17193388938903809
0.19063401222229004
0.18307733535766602
0.18744993209838867
0.17004799842834473
0.1781005859375
0.16576361656188965
0.16892218589782715
0.17036652565002441
802247111496568832
0.19588613510131836
0.18288850784301758
0.17119479179382324
0.18270492553710938
0.16604924201965332
0.16477012634277344
0.20398163795471191
0.18638896942138672
0.16683506965637207
0.16962718963623047
0.17362618446350098
0.1892857551574707
0.1717066764831543
0.1764543056488037
0.1698594093322754
0.18785357475280762
0.17694520950317383
0.2062816619873047
0.17628836631774902
0.1793227195739746
0.17223334312438965
0.16892600059509277
0.1753702163696289
0.2240135669708252
0.17011547088623047
0.18338561058044434
0.16846632957458496
0.1844642162322998
0.20563435554504395
0.18289709091186523
0.176680326461792
0.18555879592895508
0.17379403114318848
0.18880939483642578
0.1729569435119629
0.17527079582214355
0.17386126518249512
0.20847868919372559
0.17080307006835938
0.18128705024719238
0.16913437843322754
0.17502808570861816
0.16654515266418457
0.1790757179260254
0.17295384407043457
0.1800975799560547
0.16908860206604004
0.18888163566589355
0.17199492454528809
0.16698169708251953
0.16823959350585938
0.18553447723388672
0.17447853088378906
0.2380812168121338
0.2064070701599121
0.19564270973205566
0.17965078353881836
0.1835038661956787
0.1708083152770996
0.17767047882080078
0.1787099838256836
0.17557740211486816
0.18437504768371582
0.18026995658874512
0.1718142032623291
0.2056884765625
0.1904163360595703
0.19648170471191406
0.19672226905822754
0.19646263122558594
0.17104268074035645
0.2105560302734375
0.17083525657653809
0.17351770401000977
0.17664694786071777
0.1681532859802246
0.19067931175231934
0.17175054550170898
0.16846323013305664
0.17298460006713867
0.23238182067871094
0.16819381713867188
0.18421554565429688
0.17334771156311035
0.1770005226135254
0.17568182945251465
0.16404104232788086
0.182420015335083
0.17981457710266113
0.16959881782531738
0.1763322353363037
0.17192363739013672
0.18605756759643555
0.16751623153686523
0.1766529083251953
0.16502881050109863
0.18706178665161133
0.1730964183807373
0.18461036682128906
0.1640949249267578
0.19902324676513672
0.189408540725708
0.1839752197265625
0.1718158721923828
0.18470525741577148
0.17528152465820312
0.17066454887390137
0.1723461151123047
0.1756610870361328
0.1867368221282959
0.18342375755310059
0.16790056228637695
0.1810319423675537
0.18976378440856934
0.20685148239135742
0.1750168800354004
0.1977400779724121
0.21214532852172852
0.1688683032989502
0.1838974952697754
0.2144935131072998
0.17639923095703125
0.17879438400268555
0.19511651992797852
0.17641377449035645
0.1763911247253418
0.1733698844909668
0.18555736541748047
0.18396449089050293
0.17029762268066406
0.18837451934814453
0.17934799194335938
0.17543935775756836
0.1660783290863037
0.17320561408996582
0.17398977279663086
0.19228863716125488
0.17602062225341797
0.16876697540283203
0.17928385734558105
0.17761921882629395
0.3745694160461426
0.2279188632965088
0.4100065231323242
0.1807727813720703
0.17580056190490723
0.17972135543823242
0.18228483200073242
0.2909882068634033
0.17122101783752441
0.21028590202331543
0.17360830307006836
0.17833924293518066
0.17569708824157715
0.1954042911529541
0.17450237274169922
0.1745147705078125
0.17235398292541504
0.16806483268737793
0.16623902320861816
0.18759393692016602
0.17666959762573242
0.21802067756652832
0.18035650253295898
0.17589831352233887
0.1831068992614746
0.16645431518554688
0.17032074928283691
0.20465755462646484
0.2079017162322998
0.16676974296569824
0.17377400398254395
0.20804238319396973
0.22192764282226562
0.1761941909790039
0.17957329750061035
0.18099522590637207
0.17845487594604492
0.17247247695922852
0.16807198524475098
0.18847060203552246
0.1821591854095459
0.17446064949035645
0.16775846481323242
0.17803406715393066
0.1719222068786621
0.17151546478271484
0.1651315689086914
0.1886906623840332
0.18035197257995605
0.1701040267944336
0.227492094039917
0.18041491508483887
0.18116974830627441
0.17962241172790527
0.17096638679504395
0.17709136009216309
0.18023037910461426
0.17535924911499023
0.1705777645111084
0.18212580680847168
0.1685175895690918
0.16702938079833984
0.1752457618713379
0.19153738021850586
0.18311667442321777
0.17273449897766113
0.16927576065063477
0.17616724967956543
0.17726922035217285
0.16554737091064453
0.173875093460083
0.17527437210083008
0.1719226837158203
0.1779646873474121
0.18069982528686523
0.20485353469848633
775096608509886464
0.20156431198120117
0.18980789184570312
0.1770334243774414
0.18161630630493164
0.17699193954467773
0.16715216636657715
0.17580461502075195
0.18964552879333496
0.1727433204650879
0.17560958862304688
0.16913676261901855
0.17684125900268555
0.16890525817871094
0.1758711338043213
0.1713881492614746
0.19895458221435547
0.17772769927978516
0.1696317195892334
0.17947101593017578
0.17449522018432617
0.17011427879333496
0.1740570068359375
0.17926907539367676
0.17375636100769043
0.16815471649169922
0.17944931983947754
0.17185187339782715
0.17480850219726562
0.17532730102539062
0.16385364532470703
0.18706226348876953
0.17591094970703125
0.17426466941833496
770743923962707968
0.16748905181884766
0.1753089427947998
0.16976666450500488
0.1731264591217041
0.1707592010498047
0.19878387451171875
0.17613554000854492
0.17515277862548828
0.17069792747497559
0.18737101554870605
0.18012213706970215
0.16961193084716797
0.24847841262817383

0.2066338062286377
0.17713451385498047
0.16658830642700195
0.17516875267028809
0.17980670928955078
0.18259644508361816
0.176513671875
0.1679527759552002
0.17933201789855957
0.1806812286376953
0.16564297676086426
0.17017269134521484
0.2009267807006836
0.18576884269714355
0.1744232177734375
0.17455673217773438
0.19458317756652832
0.17717504501342773
0.18305134773254395
0.16585159301757812
0.20626044273376465
0.18028616905212402
0.1715106964111328
0.19031167030334473
0.1836557388305664
0.19204974174499512
0.16492772102355957
0.18448305130004883
0.20590710639953613
0.1725144386291504
0.1789402961730957
0.1764049530029297
0.18517804145812988
0.1656506061553955
0.18448567390441895
0.2089076042175293
0.1851661205291748
0.16892027854919434
0.17877840995788574
0.16985321044921875
0.18199992179870605
0.17066097259521484
0.1837751865386963
0.1786186695098877
0.1815199851989746
0.16920185089111328
0.17647004127502441
0.18191051483154297
0.21526861190795898
0.17101049423217773
0.18059349060058594
0.18704771995544434
0.18948578834533691
0.20772576332092285
0.1853029727935791
0.17961907386779785
0.18282389640808105
0.1668705940246582
0.18140220642089844
0.17004919052124023
0.17457938194274902
0.23194122314453125
0.17534470558166504
0.18992877006530762
0.2040703296661377
0.17068934440612793
0.19064807891845703
0.17857623100280762
0.17462968826293945
0.16821646690368652
0.17512178421020508
0.1696157455444336
0.18581628799438477
0.19316363334655762
0.1742568016052246
0.17018532752990723
0.18715167045593262
0.18233084678649902
0.19217467308044434
0.17278838157653809
0.17552399635314941
0.16756510734558105
0.17009902000427246
0.16973328590393066
0.18954753875732422
0.1778247356414795
0.17157459259033203
0.18300342559814453
0.17974495887756348
0.2059037685394287
0.17024779319763184
0.16611647605895996
0.18027997016906738
0.18025684356689453
0.18495559692382812
0.19060873985290527
0.20734167098999023
0.17712807655334473
0.17629480361938477
0.18315815925598145
754011816964026368
0.2055819034576416
0.18963837623596191
0.17370915412902832
0.18117761611938477
0.18972039222717285
0.17245244979858398
0.1799023151397705
0.17616772651672363
0.17769980430603027
0.23997926712036133
0.1701831817626953
0.21192717552185059
0.16581416130065918
0.17766785621643066
0.17990636825561523
0.21837258338928223
0.20655369758605957
0.16545438766479492
0.17703628540039062
0.19511795043945312
0.16869306564331055
0.1734600067138672
0.17142987251281738
0.17893600463867188
0.16785812377929688
0.18304824829101562
0.17764568328857422
0.1812291145324707
0.17960000038146973
0.17138457298278809
0.17046189308166504
0.18258380889892578
0.18928003311157227
0.16910481452941895
0.16890597343444824
0.18555641174316406
0.17046356201171875
0.17464065551757812
0.24274444580078125
0.17610478401184082
0.18332886695861816
0.17312979698181152
0.17355918884277344
0.2083439826965332
0.17863893508911133
0.16876554489135742
0.2095794677734375
0.17943930625915527
0.17198801040649414
0.1714625358581543
0.16620516777038574
0.1901853084564209
0.1666421890258789
0.17423748970031738
0.18484807014465332
0.17390656471252441
0.16977310180664062
0.1743781566619873
0.1703195571899414
0.18466877937316895
0.16413187980651855
0.22864341735839844
0.1860806941986084
0.1781151294708252
0.17343616485595703
0.17852497100830078
0.1719045639038086
0.1797194480895996
0.1703484058380127
0.17011451721191406
0.1680467128753662
0.19092035293579102
0.16965174674987793
0.17651987075805664
0.1721665859222412
0.18803000450134277
0.16788864135742188
0.1894242763519287
0.1772911548614502
0.18665170669555664
0.28731298446655273
0.1748034954071045
0.1703650951385498
0.23129773139953613
0.17422080039978027
0.16759133338928223
0.1708540916442871
0.19236278533935547
0.186356782913208
0.1702866554260254
0.18579459190368652
0.20910978317260742
0.16762495040893555
0.17693662643432617
0.17273616790771484
0.18043255805969238
0.1767578125
0.1915290355682373
0.1727898120880127
0.1917417049407959
0.5638322830200195
0.16729021072387695
0.1913588047027588
0.20521306991577148
0.19063091278076172
0.16812753677368164
0.1761021614074707
0.18121886253356934
0.1686391830444336
0.1879868507385254
0.1777057647705078
0.17875361442565918
0.1671154499053955
0.19363617897033691
0.1724834442138672
0.18021345138549805
0.17003965377807617
0.18115878105163574
0.1649775505065918
0.19223499298095703
0.20521044731140137
0.18569350242614746
0.17056679725646973
0.17476916313171387
0.18472838401794434
0.17183852195739746
0.16972565650939941
0.1746046543121338
0.1742103099822998
0.16589045524597168
0.1850595474243164
0.17901253700256348
0.1783747673034668
0.17091727256774902
0.1687030792236328
0.18755030632019043
0.16769981384277344
0.1779932975769043
0.17338228225708008
0.22050118446350098
0.19122576713562012
0.18501663208007812
0.18862295150756836
0.19414234161376953
0.16856789588928223
0.17514300346374512
0.16823315620422363
0.18163633346557617
0.1775658130645752
0.168410062789917
0.17511510848999023
0.17868328094482422
0.18500852584838867
0.18719696998596191
0.17063355445861816
0.19695830345153809
0.18345069885253906
0.17160606384277344
0.16962385177612305
0.18187618255615234
0.19800138473510742
0.17619085311889648
0.17178583145141602
0.18677139282226562
0.17177391052246094
0.17023158073425293
0.16791272163391113
0.1871025562286377
0.1689140796661377
0.1690666675567627
0.1780989170074463
0.1771411895751953
0.17535972595214844
0.1676492691040039
0.2033677101135254
0.17614006996154785
0.16701078414916992
0.16907286643981934
0.18042230606079102
0.19572925567626953
0.18285131454467773
0.16933989524841309
0.16993331909179688
0.18437767028808594
0.173828125
0.1867992877960205
0.2143261432647705
0.20811820030212402
0.1821749210357666
0.16828012466430664
0.18435311317443848
0.17913126945495605
0.1995530128479004
0.170332670211792
0.17259621620178223
0.17857933044433594
0.16924452781677246
0.17254376411437988
0.16812586784362793
0.17905116081237793
0.17847013473510742
0.16845989227294922
0.17594289779663086
0.17132258415222168
0.1644458770751953
0.170609712600708
0.16701149940490723
0.1787886619567871
0.22209477424621582
0.1983938217163086
0.2029581069946289
0.18416953086853027
0.17075681686401367
0.1813652515411377
0.1752152442932129
0.1793196201324463
0.19278478622436523
0.16907310485839844
0.17802882194519043
0.18985795974731445
0.18185758590698242
0.18980956077575684
0.16997480392456055
0.18276476860046387
0.16889381408691406
0.16921067237854004
0.18461918830871582
0.183685302734375
0.1855323314666748
0.19528770446777344
0.18875932693481445
0.19508099555969238
0.16543245315551758
0.17931675910949707
0.19006013870239258
0.2102205753326416
0.1734607219696045
0.1677241325378418
0.19031596183776855
0.18043208122253418
0.23555326461791992
0.17274951934814453
0.17373085021972656
0.18050456047058105
0.2327728271484375
0.2084674835205078
0.18807125091552734
0.1833345890045166
0.17424941062927246
0.17046403884887695
0.17435002326965332
0.18589448928833008
0.17007231712341309
0.17677903175354004
0.17505621910095215
0.1856544017791748
0.17470407485961914
0.17045974731445312
0.16845321655273438
0.20284247398376465
0.18452930450439453
0.16981053352355957
0.17197084426879883
0.1800687313079834
0.18162107467651367
0.16665172576904297
0.1790633201599121
0.2032027244567871
0.17470574378967285
0.1651468276977539
0.17416977882385254
0.26360011100769043
0.16905903816223145
0.17000770568847656
0.18281292915344238
0.1777024269104004
0.1840355396270752
0.16868042945861816
0.17691326141357422
0.18551135063171387
0.17527556419372559
0.17070388793945312
0.16590023040771484
0.22020530700683594
0.16724467277526855
0.17668962478637695
0.16889309883117676
0.1815013885498047
0.17766284942626953
0.19440555572509766
0.16982340812683105
0.1865832805633545
0.1765596866607666
0.18756413459777832
0.17572617530822754
0.19295573234558105
0.17348122596740723
0.17161822319030762
0.17125964164733887
0.20351290702819824
0.17628717422485352
0.17673444747924805
0.17859196662902832
0.17913150787353516
0.18272972106933594
0.1700725555419922
0.17701172828674316
0.20137381553649902
0.16876006126403809
0.19158673286437988
0.18171930313110352
Rate limit reached. Sleeping for: 736
741.3138480186462
0.17863750457763672
0.37142086029052734
0.1671922206878662

0.22204875946044922
0.18068981170654297
0.17466020584106445
0.28885769844055176
0.2141883373260498
0.1706862449645996
0.17777562141418457
0.1827993392944336
0.1794426441192627
0.17029833793640137
0.19948196411132812
0.1943037509918213
0.18580865859985352
0.1681499481201172
0.17290544509887695
0.16619515419006348
0.21033215522766113
0.18214821815490723
0.17220711708068848
0.17333030700683594
0.20090484619140625
0.23266220092773438
0.1782548427581787
0.17110896110534668
0.194563627243042
0.17599725723266602
0.1942439079284668
0.20034265518188477
0.17890381813049316
0.18001985549926758
0.17297697067260742
0.17166996002197266
0.18201637268066406
0.17683076858520508
0.17512035369873047
0.17779183387756348
0.2042536735534668
0.18960094451904297
0.18894577026367188
0.1926884651184082
0.18117690086364746
0.18103480339050293
0.17164993286132812
0.22774171829223633
0.1844346523284912
0.17659330368041992
0.17393922805786133
0.16634464263916016
0.18166875839233398
0.17322731018066406
0.1698160171508789
0.16917872428894043
0.18611574172973633
0.18050527572631836
0.16732358932495117
0.22508573532104492
0.18364739418029785
0.17305326461791992
0.17780256271362305
0.18665814399719238
0.18021726608276367
0.17088031768798828
0.17566657066345215
0.17424678802490234
0.22163796424865723
0.17426252365112305
0.17440438270568848
0.1673269271850586
0.18477654457092285
0.1716139316558838
0.17371511459350586
0.16582250595092773
0.18486785888671875
0.1839745044708252
0.1755826473236084
0.17021775245666504
0.19696736335754395
0.173750638961792
0.20612287521362305
0.23111462593078613
0.21800899505615234
0.17349982261657715
0.17400860786437988
0.16779255867004395
0.18251538276672363
0.16960716247558594
0.19164109230041504
0.16931629180908203
0.18015813827514648
0.2229785919189453
0.1677687168121338
0.17244410514831543
0.19879651069641113
0.18077540397644043
0.19463610649108887
0.1782209873199463
0.19452118873596191
0.17914557456970215
0.17257261276245117
0.17173266410827637
0.1853492259979248
0.17221355438232422
0.1703486442565918
0.16707992553710938
0.18802094459533691
0.1844491958618164
0.16751861572265625
0.1886141300201416
0.18225693702697754
0.1696629524230957
0.16841554641723633
0.16657733917236328
0.20657801628112793
0.2050025463104248
0.1798996925354004
0.17656517028808594
0.18039536476135254
0.1710677146911621
0.16881799697875977
0.16587209701538086
0.17854881286621094
0.16705942153930664
0.16747665405273438
0.18817758560180664
0.2078099250793457
0.22116804122924805
0.16456890106201172
0.1690051555633545
0.18169832229614258
0.17328214645385742
0.16905546188354492
0.1709146499633789
0.19192242622375488
0.17143011093139648
0.17174863815307617
0.17148256301879883
0.2112412452697754
0.17388129234313965
0.16754579544067383
0.17292428016662598
0.19938206672668457
0.18456816673278809
0.17272496223449707
0.18523263931274414
0.17809557914733887
0.16710424423217773
0.17478442192077637
0.16779708862304688
0.17965483665466309
0.1812124252319336
0.17143487930297852
0.17024707794189453
0.17516160011291504
0.17003369331359863
0.16680359840393066
0.17035675048828125
0.18819427490234375
0.1862773895263672
0.1822211742401123
0.18285584449768066
0.21216487884521484
0.17998051643371582
0.17375946044921875
0.17136216163635254
0.18059992790222168
0.17326951026916504
0.17254996299743652
0.1700592041015625
0.192002534866333
0.1740431785583496
0.1918504238128662
0.17205572128295898
0.1800224781036377
0.16795134544372559
0.18819046020507812
0.1937708854675293
0.18749070167541504
0.20389723777770996
0.17055654525756836
0.1771547794342041
0.19577693939208984
0.17358136177062988
0.16731882095336914
0.1912243366241455
0.1851668357849121
0.18782567977905273
0.1760404109954834
0.17524242401123047
0.1912698745727539
0.21960783004760742
0.20838022232055664
0.17502498626708984
0.18580293655395508
0.18367600440979004
0.1780843734741211
0.17201590538024902
0.1766223907470703
0.16933798789978027
0.1764049530029297
0.17132878303527832
0.17795586585998535
0.16707110404968262
0.24777531623840332
0.17072391510009766
0.189239501953125
0.18212532997131348
0.17323637008666992
0.19826316833496094
0.22819161415100098
0.20354914665222168
0.17341876029968262
0.1757950782775879
0.1902613639831543
0.1790323257446289
0.17034220695495605
0.16936373710632324
0.18633604049682617
0.17995214462280273
0.16555190086364746
0.17481160163879395
0.18127226829528809
0.17544984817504883
0.17595601081848145
0.1733560562133789
0.18477153778076172
0.19246435165405273
0.16506314277648926
0.1716299057006836
0.18819880485534668
0.17260456085205078
0.1737062931060791
0.17551255226135254
0.18284916877746582
0.16622328758239746
0.1753687858581543
0.17064142227172852
0.19337129592895508
0.1875898838043213
0.17332053184509277
0.1748361587524414
0.17980170249938965
0.17977452278137207
0.17451024055480957
0.19797015190124512
0.18152689933776855
0.18548202514648438
0.1806182861328125
0.17319965362548828
0.17989349365234375
0.18079924583435059
0.1705455780029297
0.17085051536560059
0.17682933807373047
0.17045164108276367
0.16652441024780273
0.1703624725341797
0.2092137336730957
0.16416668891906738
0.19306588172912598
0.17429757118225098
0.1826794147491455
0.19274067878723145
0.1676654815673828
0.1809375286102295
0.2028484344482422
0.17312312126159668
0.17240691184997559
0.17637324333190918
0.19887971878051758
0.16947031021118164
0.16706299781799316
0.1860978603363037
0.17604613304138184
0.17297673225402832
0.18602776527404785
0.1770164966583252
0.19883227348327637
0.17938709259033203
0.1760697364807129
0.18033123016357422
0.1938180923461914
0.17264723777770996
0.1881239414215088
0.16934990882873535
0.18612217903137207
0.19406914710998535
0.17101025581359863
0.17500567436218262
0.18758654594421387
0.17655563354492188
0.17375683784484863
0.1770610809326172
0.18448686599731445
0.1728804111480713
0.17798662185668945
0.17200469970703125
0.17920875549316406
0.1752476692199707
0.16603541374206543
0.18794560432434082
0.18073439598083496
0.16757440567016602
0.17754912376403809
0.18380475044250488
0.24715232849121094
0.178938627243042
0.168961763381958
0.17099404335021973
0.18805885314941406
0.17722654342651367
0.16838645935058594
0.17316246032714844
0.17740178108215332
0.1884746551513672
0.1860184669494629
0.1696770191192627
0.17878460884094238
0.1690983772277832
0.16707563400268555
0.21504640579223633
0.18184232711791992
0.19780898094177246
0.1768510341644287
0.17612004280090332
0.1815967559814453
0.18290495872497559
0.3791351318359375
0.2054140567779541
0.18816804885864258
0.1748666763305664
0.17946410179138184
0.177994966506958
0.20899271965026855
0.17983603477478027
0.19896674156188965
0.16941022872924805
0.18748092651367188
0.17708897590637207
0.18320131301879883
0.22668886184692383
0.18126964569091797
0.18044352531433105
0.1726529598236084
0.17986011505126953
0.17936468124389648
0.17194390296936035
0.166456937789917
0.21335411071777344
0.21924376487731934
0.18709158897399902
0.16627240180969238
0.16500043869018555
0.21495413780212402
0.17943596839904785
0.17291998863220215
0.1829080581665039
0.18353056907653809
0.17410564422607422
0.16903090476989746
0.18674635887145996
0.23586773872375488
0.17711925506591797
0.17702031135559082
0.17236876487731934
0.21033048629760742
0.17189407348632812
0.17180109024047852
0.18761658668518066
0.18139362335205078
0.17206025123596191
0.20006513595581055
0.16789817810058594
0.18271136283874512
0.16844916343688965
0.1889190673828125
0.18132233619689941
0.17987561225891113
0.16881084442138672
0.18745851516723633
0.16491270065307617
0.1845383644104004
0.17327213287353516
0.17911696434020996
0.17386698722839355
0.20736479759216309
0.17873597145080566
0.18522119522094727
0.16722750663757324
0.21205878257751465
0.18447351455688477
0.17608046531677246
0.16675949096679688
0.18916749954223633
0.17184805870056152
0.1687793731689453
0.1928715705871582
0.18049263954162598
0.18024110794067383
0.18335986137390137
0.1875627040863037
0.22090363502502441
0.2059497833251953
0.20713210105895996
0.17759370803833008
0.18791961669921875
0.17574310302734375
0.17299294471740723
0.18286490440368652
0.18853116035461426
0.17714238166809082
0.18431544303894043
0.18613839149475098
0.23679471015930176
0.2186586856842041
0.1685171127319336

0.21214079856872559
0.1920182704925537
0.1729435920715332
0.17756080627441406
0.1712205410003662
0.18949151039123535
0.18455147743225098
0.1733102798461914
0.19268798828125
0.17970776557922363
0.1685779094696045
0.18871045112609863
0.21455931663513184
0.18598341941833496
0.19292163848876953
0.1754460334777832
0.1736745834350586
0.18327808380126953
0.2190384864807129
0.1844775676727295
0.16997838020324707
0.18457841873168945
0.17537522315979004
0.18498682975769043
0.19057750701904297
0.2073659896850586
0.17458057403564453
0.17350125312805176
0.18697309494018555
0.18671011924743652
0.1659848690032959
0.18201661109924316
0.19594287872314453
0.2435152530670166
0.17142748832702637
0.17548847198486328
0.18217945098876953
0.1811354160308838
0.1679220199584961
0.1787407398223877
0.3847646713256836
0.1829366683959961
0.1787111759185791
0.17229318618774414
0.1773068904876709
0.19879746437072754
0.18902063369750977
0.17162466049194336
0.27100634574890137
0.17821764945983887
0.17044568061828613
0.20473885536193848
0.18423223495483398
0.18638086318969727
0.17276644706726074
0.1759641170501709
0.16998720169067383
0.18115806579589844
0.17233705520629883
0.17341184616088867
0.17908930778503418
0.17937994003295898
0.17171001434326172
0.20837116241455078
0.17711400985717773
0.20189380645751953
0.18480682373046875
0.16847658157348633
0.17057275772094727
0.18729519844055176
0.1783733367919922
0.1895902156829834
0.18799471855163574
0.2008662223815918
0.17350387573242188
0.18011784553527832
0.23439693450927734
0.18038225173950195
0.16800856590270996
0.16678309440612793
0.17493247985839844
0.2080228328704834
0.16683006286621094
0.17251157760620117
0.17810273170471191
0.18187212944030762
0.16995620727539062
0.16842985153198242
0.1919560432434082
0.1839611530303955
0.17736077308654785
0.17197394371032715
0.21457266807556152
0.1841747760772705
0.1790323257446289
0.1681509017944336
0.1820986270904541
0.20720744132995605
0.1708683967590332
0.174241304397583
0.17859196662902832
0.23995113372802734
0.1724073886871338
0.17508316040039062
0.21904778480529785
0.1837916374206543
0.1692657470703125
0.16623950004577637
0.18213772773742676
0.1789388656616211
0.16782283782958984
0.16433405876159668
0.1736290454864502
0.1957387924194336
0.1813209056854248
0.17150425910949707
0.1689283847808838
0.1868152618408203
0.1740555763244629
0.17244958877563477
0.19800114631652832
0.18103384971618652
0.18823719024658203
0.24919676780700684
0.18823003768920898
0.1861116886138916
0.17401766777038574
0.17438936233520508
0.16861176490783691
0.20997977256774902
0.16849875450134277
0.1721196174621582
0.1761460304260254
0.6067132949829102
0.1994624137878418
0.16993141174316406
0.18784737586975098
0.17900490760803223
0.17304730415344238
0.17459630966186523
0.20012331008911133
0.17479968070983887
0.17200136184692383
0.2035365104675293
0.1870899200439453
0.17023372650146484
0.1702134609222412
0.18886995315551758
0.2279057502746582
0.1757500171661377
0.18296265602111816
0.17869234085083008
0.18966364860534668
0.17147207260131836
0.1732494831085205
0.19421076774597168
0.2027297019958496
0.1784224510192871
0.17361068725585938
0.18414998054504395
0.19252777099609375
0.19862842559814453
0.16762232780456543
0.18256568908691406
0.21819448471069336
0.1784682273864746
0.18619751930236816
0.1770787239074707
0.18153095245361328
0.1717982292175293
0.18258905410766602
0.17177653312683105
0.18826508522033691
0.17131328582763672
0.1705641746520996
0.2876150608062744
0.1918802261352539
0.16765093803405762
0.18057584762573242
0.17206668853759766
0.22761011123657227
0.17995452880859375
0.172576904296875
0.17380976676940918
0.19164323806762695
0.19214725494384766
0.1714169979095459
0.17324018478393555
0.1855001449584961
0.17832398414611816
0.17017841339111328
0.1771101951599121
0.19803476333618164
0.1781325340270996
0.17572712898254395
0.2053823471069336
0.18703794479370117
0.1750340461730957
0.17684292793273926
0.18331384658813477
0.20930004119873047
0.21013689041137695
0.16981792449951172
0.17183256149291992
0.1934034824371338
0.1848132610321045
0.16748952865600586
0.18534064292907715
0.18761491775512695
0.1699204444885254
0.18717646598815918
0.16981792449951172
0.19327473640441895
0.1785876750946045
0.17110633850097656
0.1758744716644287
0.1871490478515625
0.17211222648620605
0.1908552646636963
0.17998790740966797
0.19724559783935547
0.17815899848937988
0.17133593559265137
0.17050957679748535
0.19190096855163574
0.18160271644592285
0.1748218536376953
0.17508363723754883
0.22705292701721191
0.18172621726989746
0.4893183708190918
0.16847777366638184
0.3932530879974365
0.17598509788513184
0.1717548370361328
0.22247529029846191
0.1899423599243164
0.218123197555542
0.18605351448059082
0.17804908752441406
0.2190392017364502
0.17654728889465332
0.17822623252868652
0.1657242774963379
0.20301604270935059
0.17227506637573242
0.1701362133026123
0.1752481460571289
0.2654709815979004
0.18674993515014648
0.1810450553894043
0.2052295207977295
0.18968963623046875
0.18445682525634766
0.18494296073913574
0.16841936111450195
0.19653558731079102
0.19650936126708984
0.16740846633911133
0.17197108268737793
0.18296003341674805
0.18680071830749512
0.17181897163391113
0.17995405197143555
0.1924302577972412
0.17543864250183105
0.19199585914611816
0.17068266868591309
0.1917867660522461
0.17700910568237305
0.1710669994354248
0.17076492309570312
0.23151040077209473
0.16968417167663574
0.16795921325683594
0.17665696144104004
0.2395923137664795
0.17949628829956055
0.17873430252075195
0.18016457557678223
0.1911318302154541
0.1713087558746338
0.18196678161621094
0.1846158504486084
0.18925857543945312
0.16916513442993164
0.18757247924804688
0.17768049240112305
0.19147253036499023
0.1767425537109375
0.17644858360290527
0.180084228515625
0.188032865524292
0.17639541625976562
0.1730051040649414
0.18318486213684082
0.18684625625610352
0.17787742614746094
0.17076420783996582
0.16859149932861328
0.19171547889709473
0.21877741813659668
0.17238569259643555
0.17016077041625977
0.1887364387512207
0.17069292068481445
0.17343449592590332
0.16717791557312012
0.18851470947265625
0.17078089714050293
0.1792893409729004
0.17209291458129883
0.20542597770690918
0.2371976375579834
0.171372652053833
0.18153095245361328
0.1977076530456543
0.18539762496948242
0.16960501670837402
0.17173504829406738
0.20889568328857422
0.17012333869934082
0.17482256889343262
0.1800985336303711
0.2264106273651123
0.1745929718017578
0.1811995506286621
0.17099285125732422
0.18819642066955566
0.1731729507446289
0.17309975624084473
0.21385550498962402
0.2104036808013916
0.2054154872894287
0.17164969444274902
0.17212700843811035
0.20599150657653809
0.1902024745941162
0.20654916763305664
0.3901031017303467
0.19989657402038574
0.17739462852478027
0.18486666679382324
0.1782371997833252
0.20102810859680176
0.19561028480529785
0.187546968460083
0.1726067066192627
0.1928396224975586
0.1715073585510254
0.17704319953918457
0.1821136474609375
0.18904590606689453
0.17988181114196777
0.1947770118713379
0.18980884552001953
0.19210219383239746
0.18774724006652832
0.20233845710754395
0.17160892486572266
0.19640302658081055
0.1749567985534668
0.1721639633178711
0.16652560234069824
0.21320724487304688
0.19179749488830566
0.1757338047027588
0.17039251327514648
0.18971681594848633
0.18139123916625977
0.17249679565429688
0.20824575424194336
0.24277949333190918
0.18030381202697754
0.1909923553466797
0.18424057960510254
0.20245671272277832
0.2612276077270508
0.17454266548156738
0.17204904556274414
0.190382719039917
0.18133258819580078
0.17083740234375
0.19652295112609863
0.19499444961547852
0.18816542625427246
0.1708517074584961
0.17198491096496582
0.18927645683288574
0.1719369888305664
0.17130637168884277
0.17510318756103516
0.19844436645507812
0.18330788612365723
0.17264461517333984
0.20995306968688965
0.1931297779083252
0.1743941307067871
0.1716451644897461
0.18014240264892578
0.19637274742126465
0.209181547164917
0.1704273223876953
0.18853139877319336
0.19002580642700195
0.17110109329223633
0.17518305778503418
0.1708815097808838
0.20723843574523926
0.17517328262329102
0.1704392433166504
0.17351293563842773
0.2298905849456787
0.17464447021484375
0.20542454719543457
0.17904162406921387
0.19350481033325195
0.17379379272460938

0.18838167190551758
0.17815446853637695
0.23294377326965332
0.18778514862060547
0.19479990005493164
0.17362499237060547
0.19617247581481934
0.16855669021606445
0.16967320442199707
0.1696453094482422
0.21646785736083984
0.2038402557373047
0.1763598918914795
0.16756653785705566
0.19014978408813477
0.17922687530517578
0.19054102897644043
0.17580199241638184
0.18791961669921875
0.17099976539611816
0.23263955116271973
0.19182991981506348
0.20288777351379395
0.18204569816589355
0.1725752353668213
0.18310070037841797
0.19353699684143066
0.18004226684570312
0.19771957397460938
0.17514657974243164
0.18608975410461426
0.17335152626037598
0.17260360717773438
0.20509052276611328
0.18488574028015137
0.1697545051574707
0.1712327003479004
0.17011117935180664
0.1970672607421875
0.17627596855163574
0.1695256233215332
0.1663811206817627
0.19266200065612793
0.17843008041381836
0.17798590660095215
0.18079400062561035
0.18574190139770508
0.1779639720916748
0.17820191383361816
0.17061161994934082
0.22481107711791992
0.17456579208374023
0.17392468452453613
0.17510604858398438
0.18824195861816406
0.1699693202972412
0.19070816040039062
0.16844677925109863
0.20801115036010742
0.17139863967895508
0.169846773147583
0.17243218421936035
0.19488263130187988
Rate limit reached. Sleeping for: 733
738.3214638233185
0.17441082000732422
0.16955304145812988
0.18915629386901855
0.1741499900817871
0.17877960205078125
0.17520952224731445
0.23820853233337402
0.17164397239685059
0.23802542686462402
0.17180299758911133
0.19054532051086426
0.171295166015625
0.16981053352355957
0.17341160774230957
0.1823585033416748
0.17943191528320312
0.19304466247558594
0.17488813400268555
0.18635988235473633
0.17461228370666504
0.19373178482055664
0.1823716163635254
0.1882925033569336
0.17450356483459473
0.17515349388122559
0.18996667861938477
0.18688297271728516
0.1705002784729004
0.23502349853515625
0.16457581520080566
0.2146775722503662
0.16634368896484375
0.18265604972839355
0.18009519577026367
0.23897552490234375
0.1740882396697998
0.19177460670471191
0.1908407211303711
0.20465946197509766
0.18260908126831055
0.1755669116973877
0.18034076690673828
0.1875746250152588
0.17336225509643555
0.17321395874023438
0.16961884498596191
0.18646812438964844
0.1938924789428711
0.23218250274658203
0.1718158721923828
0.29626917839050293
0.17080354690551758
0.18865585327148438
0.17584681510925293
0.19393086433410645
0.1742722988128662
0.17188024520874023
0.1694035530090332
0.22395777702331543
0.17657804489135742
0.17278766632080078
0.17354679107666016
0.19215703010559082
0.1744551658630371
0.18438267707824707
0.18460869789123535
0.19000720977783203
0.18809199333190918
0.17997980117797852
0.1716005802154541
0.19709205627441406
0.1774616241455078
0.1697227954864502
0.19882845878601074
0.1918201446533203
0.17784500122070312
0.2063431739807129
0.1746523380279541
0.1868605613708496
0.1727125644683838
0.1687004566192627
0.18720626831054688
0.23532342910766602
0.1780259609222412
0.167022705078125
0.23105144500732422
0.2313365936279297
0.17547106742858887
0.17102885246276855
0.16962122917175293
0.19385933876037598
0.16824030876159668
0.17190861701965332
0.1758270263671875
0.1858360767364502
0.17351722717285156
0.18236422538757324
0.17230677604675293
0.18850302696228027
0.18632197380065918
0.1757347583770752
0.18625187873840332
0.18101906776428223
0.16879653930664062
0.17054057121276855
0.25276780128479004
0.19927358627319336
0.1708076000213623
0.17781448364257812
0.16997385025024414
0.19452619552612305
0.18553853034973145
0.1743173599243164
0.17132902145385742
0.20728778839111328
0.17637324333190918
0.17253422737121582
0.21067571640014648
0.1907482147216797
0.18265390396118164
0.17812514305114746
0.19025015830993652
0.18886995315551758
0.17670845985412598
0.18278241157531738
0.17073535919189453
0.19171905517578125
0.17754864692687988
0.17744731903076172
0.17287516593933105
0.25022125244140625
0.17988085746765137
0.1975231170654297
0.18647527694702148
0.19740748405456543
0.18410253524780273
0.18142199516296387
0.1706256866455078
0.19139957427978516
0.22231292724609375
0.18210887908935547
0.20123529434204102
0.19382095336914062
0.18381953239440918
0.17537498474121094
0.17325711250305176
0.19413018226623535
0.17669105529785156
0.17221307754516602
0.18875789642333984
0.18717265129089355
0.1677398681640625
0.1757526397705078
0.17407870292663574
0.20968842506408691
0.17289280891418457
0.19512486457824707
0.16965627670288086
0.18743324279785156
0.23638248443603516
0.18340396881103516
0.18225836753845215
0.19234728813171387
0.16988205909729004
0.1765425205230713
0.16859698295593262
0.1866927146911621
0.2298905849456787
0.17545580863952637
0.17893385887145996
0.18648099899291992
0.16896295547485352
0.17300987243652344
0.19229650497436523
0.18747329711914062
0.18305516242980957
0.17272329330444336
0.19637632369995117
0.22377872467041016
0.17194080352783203
0.17318320274353027
0.1812734603881836
0.19275236129760742
0.1696467399597168
0.21513938903808594
0.20546388626098633
0.19075655937194824
0.17323756217956543
0.21124792098999023
0.18964695930480957
0.21548676490783691
0.17583489418029785
0.1695845127105713
0.17368125915527344
0.20317530632019043
0.17702221870422363
0.17251896858215332
0.1904001235961914
0.1880018711090088
0.1692030429840088
0.1722872257232666
0.18103909492492676
0.19961857795715332
0.17209148406982422
0.17238473892211914
0.1705787181854248
0.1950397491455078
0.17197036743164062
0.2285597324371338
0.17267322540283203
0.22322845458984375

In [41]:
#Separate the json part of each tweepy status and add it to the list
my_list_of_dicts = []
for each_json_tweet in list_of_tweets:
    my_list_of_dicts.append(each_json_tweet._json)
#Write list to a txt file
with open('tweet_json.txt', 'w') as file:
        file.write(json.dumps(my_list_of_dicts, indent=4))

In [42]:
#Create DataFrame from the tweet_json.txt file:
my_demo_list = []
with open('tweet_json.txt', encoding='utf-8') as json_file:  
    all_data = json.load(json_file)
    for each_dictionary in all_data:
        tweet_id = each_dictionary['id']
        whole_tweet = each_dictionary['text']
        only_url = whole_tweet[whole_tweet.find('https'):]
        favorite_count = each_dictionary['favorite_count']
        retweet_count = each_dictionary['retweet_count'] 
        created_at = each_dictionary['created_at']
        whole_source = each_dictionary['source']
        only_device = whole_source[whole_source.find('rel="nofollow">') + 15:-4]
        source = only_device
        retweeted_status = each_dictionary['retweeted_status'] = each_dictionary.get('retweeted_status', 'Original tweet')
        if retweeted_status == 'Original tweet':
            url = only_url
        else:
            retweeted_status = 'This is a retweet'
            url = 'This is a retweet'
            
            my_demo_list.append({'tweet_id': str(tweet_id),
                             'favorite_count': int(favorite_count),
                             'retweet_count': int(retweet_count),
                             'url': url,
                             'created_at': created_at,
                             'source': source,
                             'retweeted_status': retweeted_status,
                            })
        tweet_json = pd.DataFrame(my_demo_list, columns = ['tweet_id', 'favorite_count', 
                                                       'retweet_count', 'created_at',
                                                       'source', 'retweeted_status', 'url'])

# Assess
# 1) twitter_archive

In [43]:
#Assess the twitter_archive dataframe
#Write the quality and tideness issues.
#Summarize the findings after completing visual and programatic assessment
#Arranging the data for better visualization
pd.options.display.max_colwidth = 10000
twitter_archive

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643555336193/photo/1,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV",NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421306343426/photo/1,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181378084864/photo/1,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD36da7qLQ,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557279858688/photo/1,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek https://t.co/AtUZn91f7f",NaN,NaN,NaN,"https://twitter.com/dog_rates/status/891327558926688256/photo/1,https://twitter.com/dog_rates/status/891327558926688256/photo/1",12,10,Franklin,None,None,None,None
5,891087950875897856,NaN,NaN,2017-07-29 00:08:17 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek https://t.co/kQ04fDDRmh,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891087950875897856/photo/1,13,10,None,None,None,None,None
6,890971913173991426,NaN,NaN,2017-07-28 16:27:12 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Meet Jax. He enjoys ice cream so much he gets nervous around it. 13/10 help Jax enjoy more things by clicking below\n\nhttps://t.co/Zr4hWfAs1H https://t.co/tVJBRMnhxl,NaN,NaN,NaN,"https://gofundme.com/ydvmve-surgery-for-jax,https://twitter.com/dog_rates/status/890971913173991426/photo/1",13,10,Jax,None,None,None,None
7,890729181411237888,NaN,NaN,2017-07-28 00:22:40 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",When you watch your owner call another dog a good boy but then they turn back to you and say you're a great boy. 13/10 https://t.co/v0nONBcwxq,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/890729181411237888/photo/1,https://twitter.com/dog_rates/status/890729181411237888/photo/1",13,10,None,None,None,None,None
8,890609185150312448,NaN,NaN,2017-07-27 16:25:51 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Zoey. She doesn't want to be one of the scary sharks. Just wants to be a snuggly pettable boatpet. 13/10 #BarkWeek https://t.co/9TwLuAGH0b,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890609185150312448/photo/1,13,10,Zoey,None,None,None,None
9,890240255349198849,NaN,NaN,2017-07-26 15:59:51 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Cassie. She is a college pup. Studying international doggo communication and stick theory. 14/10 so elegant much sophisticate https://t.co/t1bfwz5S2A,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890240255349198849/photo/1,14,10,Cassie,doggo,None,None,None
10,890006608113172480,NaN,NaN,2017-07-26 00:31:25 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Koda. He is a South Australian deckshark. Deceptively deadly. Frighteningly majestic. 13/10 would risk a petting #BarkWeek https://t.co/dVPW0B0Mme,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/890006608113172480/photo/1,https://twitter.com/dog_rates/status/890006608113172480/photo/1",13,10,Koda,None,None,None,None
11,889880896479866881,NaN,NaN,2017-07-25 16:11:53 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Bruno. He is a service shark. Only gets out of the water to assist you. 13/10 terrifyingly good boy https://t.co/u1XPQMl29g,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889880896479866881/photo/1,13,10,Bruno,None,None,None,None
12,889665388333682689,NaN,NaN,2017-07-25 01:55:32 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here's a puppo that seems to be on the fence about something haha no but seriously someone help her. 13/10 https://t.co/BxvuXk0UCm,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388333682689/photo/1,13,10,None,None,None,None,puppo
13,889638837579907072,NaN,NaN,2017-07-25 00:10:02 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Ted. He does his best. Sometimes that's not enough. But it's ok. 12/10 would assist https://t.co/f8dEDcrKSR,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/889638837579907072/photo/1,https://twitter.com/dog_rates/status/889638837579907072/photo/1",12,10,Ted,None,None,None,None
14,889531135344209921,NaN,NaN,2017-07-24 17:02:04 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Stuart. He's sporting his favorite fanny pack. Secretly filled with bones only. 13/10 puppared puppo #BarkWeek https://t.co/y70o6h3isq,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889531135344209921/photo/1,13,10,Stuart,None,None,None,puppo
15,889278841981685760,NaN,NaN,2017-07-24 00:19:32 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Oliver. You're witnessing one of his many brutal attacks. Seems to be playing with his victim. 13/10 fr*ckin frightening #BarkWeek https://t.co/WpHvrQedPb,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889278841981685760/video/1,13,10,Oliver,None,None,None,None
16,888917238123831296,NaN,NaN,2017-07-23 00:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Jim. He found a fren. Taught him how to sit like the good boys. 12/10 for both https://t.co/chxruIOUJN,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888917238123831296/photo/1,12,10,Jim,None,None,None,None
17,888804989199671297,NaN,NaN,2017-07-22 16:56:37 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Zeke. He has a new stick. Very proud of it. Would like you to throw it for him without taking it. 13/10 would do my best https://t.co/HTQ77yNQ5K,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/888804989199671297/photo/1,https://twitter.com/dog_rates/status/888804989199671297/photo/1",13,10,Zeke,None,None,None,None
18,888554962724278272,NaN,NaN,2017-07-22 00:23:06 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Ralphus. He's powering up. Attempting maximum borkdrive. 13/10 inspirational af https://t.co/YnYAFCTTiK,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/888554962724278272/photo/1,https://twitter.com/dog_rates/status/888554962724278272/photo/1,https://twitter.com/dog_rates/status/888554962724278272/photo/1,https://twitter.com/dog_rates/status/888554962724278272/photo/1",13,10,Ralphus,None,None,None,None
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",RT @dog_rates: This is Canela. She attempted some fancy porch pics. They were unsuccessful. 13/10 someone help her https://t.co/cLyzpcUcMX,8.874740e+17,4.196984e+09,2017-07-19 00:47:34 +0000,"https://twitter.com/dog_rates/status/887473957103951883/photo/1,https://twitter.com/dog_rates/status/887473957103951883/photo/1,https://twitter.com/dog_rates/status/887473957103951883/photo/1,https://twitter.com/dog_rates/status/887473957103951883/photo/1",13,10,Canela,None,None,None,None
20,888078434458587136,NaN,NaN,2017-07-20 16:49:33 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Gerald. He was just told he didn't get the job he interviewed for. A h*ckin injustice. 12/10 didn't want the job anyway https://t.co/DK7iDPfuRX,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/888078434458587136/photo/1,https://twitter.com/dog_rates/status/888078434458587136/photo/1",12,10,Gerald,None,None,None,None
21,887705289381826560,NaN,NaN,2017-07-19 16:06:48 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Jeffrey. He has a monopoly on the pool noodles. Currently running a 'boop for two' midweek sale. 13/10 h*ckin strategic https://t.co/PhrUk20Q64,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887705289381826560/photo/1,13,10,Jeffrey,None,None,None,None
22,887517139158093824,NaN,NaN,2017-07-19 03:39:09 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: roxy.thedoxy) https://t.co/20VrLAA8ba,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887517139158093824/video/1,14,10,such,None,None,None,None
23,887473957103951883,NaN,NaN,2017-07-19 00:47:34 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Canela. She attempted some fancy porch pics. They were unsuccessful. 13/10 someone help her https://t.co/cLyzpcUcMX,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/887473957103951883/photo/1,https://twitter.com/dog_rates/status/887473957103951883/photo/1",13,10,Canela,None,None,None,None
24,887343217045368832,NaN,NaN,2017-07-18 16:08:03 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo) https://t.co/WZqNqygEyV,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887343217045368832/video/1,13,10,None,None,None,None,None
25,887101392804085760,NaN,NaN,2017-07-18 00:07:08 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This... is a Jubilant Antarctic House Bear. We only rate dogs. Please only send dogs. Thank you... 12/10 would suffocate in floof https://t.co/4Ad1jzJSdp,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887101392804085760/photo/1,12,10,None,None,None,None,None
26,886983233522544640,NaN,NaN,2017-07-17 16:17:36 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Maya. She's very shy. Rarely leaves her cup. 13/10 would find her an environment to thrive in https://t.co/I6oNy0CgiT,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/886983233522544640/photo/1,https://twitter.com/dog_rates/status/886983233522544640/photo/1",13,10,Maya,None,None,None,None
27,886736880519319552,NaN,NaN,2017-07-16 23:58:41 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Mingus. He's a wonderful father to his smol pup. Confirmed 13/10, but he needs your help\n\nhttps://t.co/bVi0Yr4Cff https://t.co/ISvKOSkd5b",NaN,NaN,NaN,"https://www.gofundme.com/mingusneedsus,https://twitter.com/dog_rates/status/886736880519319552/photo/1,https://twitter.com/dog_rates/status/886736880519319552/photo/1",13,10,Mingus,None,None,None,None
28,886680336477933568,NaN,NaN,2017-07-16 20:14:00 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Derek. He's late for a dog meeting. 13/10 pet...al to the metal https://t.co/BCoWue0abA,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886680336477933568/photo/1,13,10,Derek,None,None,None,None
29,886366144734445568,NaN,NaN,2017-07-15 23:25:31 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Roscoe. Another pupper fallen victim to spontaneous tongue ejections. Get the BlepiPen immediate. 12/10 deep breaths Roscoe https://t.co/RGE08MIJox,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/886366144734445568/photo/1,https://twitter.com/dog_rates/status/886366144734445568/photo/1",12,10,Roscoe,None,None,pupper,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,666411507551481857,NaN,NaN,2015-11-17 00:24:19 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is quite the dog. Gets really excited when not in water. Not very soft tho. Bad at fetch. Can't do tricks. 2/10 https://t.co/aMCTNWO94t,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666411507551481857/photo/1,2,10,quite,None,None,None,None
2327,666407126856765440,NaN,NaN,2015-11-17 00:06:54 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is a southern Vesuvius bumblegruff. Can drive a truck (wow). Made friends with 5 other nifty dogs (neat). 7/10 https://t.co/LopTBkKa8h,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666407126856765440/photo/1,7,10,a,None,None,None,None
2328,666396247373291520,NaN,NaN,2015-11-16 23:23:41 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Oh goodness. A super rare northeast Qdoba kangaroo mix. Massive feet. No pouch (disappointing). Seems alert. 9/10 https://t.co/Dc7b0E8qFE,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666396247373291520/photo/1,9,10,None,None,None,None,None
2329,666373753744588802,NaN,NaN,2015-11-16 21:54:18 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Those are sunglasses and a jean jacket. 11/10 dog cool af https://t.co/uHXrPkUEyl,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666373753744588802/photo/1,11,10,None,None,None,None,None
2330,666362758909284353,NaN,NaN,2015-11-16 21:10:36 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Unique dog here. Very small. Lives in container of Frosted Flakes (?). Short legs. Must be rare 6/10 would still pet https://t.co/XMD9CwjEnM,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666362758909284353/photo/1,6,10,None,None,None,None,None
2331,666353288456101888,NaN,NaN,2015-11-16 20:32:58 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a mixed Asiago from the Galápagos Islands. Only one ear working. Big fan of marijuana carpet. 8/10 https://t.co/tltQ5w9aUO,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666353288456101888/photo/1,8,10,None,None,None,None,None
2332,666345417576210432,NaN,NaN,2015-11-16 20:01:42 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Look at this jokester thinking seat belt laws don't apply to him. Great tongue tho 10/10 https://t.co/VFKG1vxGjB,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666345417576210432/photo/1,10,10,None,None,None,None,None
2333,666337882303524864,NaN,NaN,2015-11-16 19:31:45 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is an extremely rare horned Parthenon. Not amused. Wears shoes. Overall very nice. 9/10 would pet aggressively https://t.co/QpRjllzWAL,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666337882303524864/photo/1,9,10,an,None,None,None,None
2334,666293911632134144,NaN,NaN,2015-11-16 16:37:02 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is a funny dog. Weird toes. Won't come down. Loves branch. Refuses to eat his food. Hard to cuddle with. 3/10 https://t.co/IIXis0zta0,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666293911632134144/photo/1,3,10,a,None,None,None,None
2335,666287406224695296,NaN,NaN,2015-11-16 16:11:11 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is an Albanian 3 1/2 legged Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 https://t.co/d9NcXFKwLv,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666287406224695296/photo/1,1,2,an,None,None,None,None
2336,666273097616637952,NaN,NaN,2015-11-16 15:14:19 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Can take selfies 11/10 https://t.co/ws2AMaNwPW,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666273097616637952/photo/1,11,10,None,None,None,None,None
2337,666268910803644416,NaN,NaN,2015-11-16 14:57:41 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Very concerned about fellow dog trapped in computer. 10/10 https://t.co/0yxApIikpk,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666268910803644416/photo/1,10,10,None,None,None,None,None
2338,666104133288665088,NaN,NaN,2015-11-16 04:02:55 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10 https://t.co/Asgdc6kuLX,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666104133288665088/photo/1,1,10,None,None,None,None,None
2339,666102155909144576,NaN,NaN,2015-11-16 03:55:04 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Oh my. Here you are seeing an Adobe Setter giving birth to twins!!! The world is an amazing place. 11/10 https://t.co/11LvqN4WLq,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666102155909144576/photo/1,11,10,None,None,None,None,None
2340,666099513787052032,NaN,NaN,2015-11-16 03:44:34 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Can stand on stump for what seems like a while. Built that birdhouse? Impressive. Made friends with a squirrel. 8/10 https://t.co/Ri4nMTLq5C,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666099513787052032/photo/1,8,10,None,None,None,None,None
2341,666094000022159362,NaN,NaN,2015-11-16 03:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This appears to be a Mongolian Presbyterian mix. Very tired. Tongue slip confirmed. 9/10 would lie down with https://t.co/mnioXo3IfP,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666094000022159362/photo/1,9,10,None,None,None,None,None
2342,666082916733198337,NaN,NaN,2015-11-16 02:38:37 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a well-established sunblockerspaniel. Lost his other flip-flop. 6/10 not very waterproof https://t.co/3RU6x0vHB7,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666082916733198337/photo/1,6,10,None,None,None,None,None

In [44]:
#Use the info method to assess the DataFrame
twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [45]:
# There are missing records in the expanded_urls column. 
#They are replies since replies don't have url in the Twitter API
twitter_archive[twitter_archive['expanded_urls'].isnull()].loc[:,['expanded_urls', 
                                                                  'in_reply_to_status_id', 
                                                                  'in_reply_to_user_id',
                                                                 'retweeted_status_id']]

,expanded_urls,in_reply_to_status_id,in_reply_to_user_id,retweeted_status_id
30,NaN,8.862664e+17,2.281182e+09,NaN
55,NaN,8.816070e+17,4.738443e+07,NaN
64,NaN,8.795538e+17,3.105441e+09,NaN
113,NaN,8.707262e+17,1.648776e+07,NaN
148,NaN,8.634256e+17,7.759620e+07,NaN
179,NaN,8.571567e+17,1.806710e+08,NaN
185,NaN,NaN,NaN,8.563302e+17
186,NaN,8.562860e+17,2.792810e+08,NaN
188,NaN,8.558616e+17,1.943518e+08,NaN
189,NaN,8.558585e+17,1.361572e+07,NaN
218,NaN,8.503288e+17,2.195506e+07,NaN
228,NaN,8.482121e+17,4.196984e+09,NaN
234,NaN,8.476062e+17,4.196984e+09,NaN
274,NaN,8.406983e+17,8.405479e+17,NaN
290,NaN,8.381455e+17,2.195506e+07,NaN
291,NaN,8.380855e+17,2.894131e+09,NaN
313,NaN,8.352460e+17,2.625958e+07,NaN
342,NaN,8.320875e+17,3.058208e+07,NaN
346,NaN,8.319030e+17,2.068372e+07,NaN
375,NaN,NaN,NaN,NaN
387,NaN,8.265984e+17,4.196984e+09,NaN
409,NaN,8.233264e+17,1.582854e+09,NaN
427,NaN,8.211526e+17,1.132119e+08,NaN
498,NaN,8.131273e+17,4.196984e+09,NaN
513,NaN,8.116272e+17,4.196984e+09,NaN
570,NaN,8.018543e+17,1.185634e+07,NaN
576,NaN,8.008580e+17,2.918590e+08,NaN
611,NaN,7.971238e+17,2.916630e+07,NaN
701,NaN,7.727430e+17,7.305050e+17,NaN
707,NaN,NaN,NaN,NaN
843,NaN,7.667118e+17,4.196984e+09,NaN
857,NaN,7.638652e+17,1.584641e+07,NaN
967,NaN,7.501805e+17,4.717297e+09,NaN
1005,NaN,7.476487e+17,4.196984e+09,NaN
1080,NaN,7.384119e+17,3.589728e+08,NaN
1295,NaN,7.079801e+17,2.319108e+09,NaN
1345,NaN,7.044857e+17,2.878549e+07,NaN
1445,NaN,NaN,NaN,NaN
1446,NaN,6.964887e+17,4.196984e+09,NaN
1474,NaN,6.936422e+17,4.196984e+09,NaN
1479,NaN,6.935722e+17,1.198989e+09,NaN
1497,NaN,6.924173e+17,4.196984e+09,NaN
1523,NaN,6.903413e+17,4.670367e+08,NaN
1598,NaN,6.860340e+17,4.196984e+09,NaN
1605,NaN,6.855479e+17,4.196984e+09,NaN
1618,NaN,6.849598e+17,4.196984e+09,NaN
1663,NaN,6.827884e+17,4.196984e+09,NaN
1689,NaN,6.813394e+17,4.196984e+09,NaN
1774,NaN,6.780211e+17,4.196984e+09,NaN
1819,NaN,6.765883e+17,4.196984e+09,NaN
1844,NaN,6.758457e+17,4.196984e+09,NaN
1895,NaN,6.747400e+17,4.196984e+09,NaN
1905,NaN,6.744689e+17,4.196984e+09,NaN
1914,NaN,6.658147e+17,1.637468e+07,NaN
1940,NaN,6.737159e+17,4.196984e+09,NaN
2038,NaN,6.715449e+17,4.196984e+09,NaN
2149,NaN,6.693544e+17,4.196984e+09,NaN
2189,NaN,6.689207e+17,2.143566e+07,NaN
2298,NaN,6.670655e+17,4.196984e+09,NaN

In [46]:
#Four non-url tweets are not replies. 
my_non_url_non_replies_ids = twitter_archive.iloc[[185, 375, 707, 1445],:].tweet_id
twitter_archive.iloc[[185, 375, 707, 1445],:]

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
185,856330835276025856,NaN,NaN,2017-04-24 02:15:55 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",RT @Jenna_Marbles: @dog_rates Thanks for rating my cermets 14/10 wow I'm so proud I watered them so much,8.563302e+17,66699013.0,2017-04-24 02:13:14 +0000,NaN,14,10,None,None,None,None,None
375,828361771580813312,NaN,NaN,2017-02-05 21:56:51 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Twitter Web Client</a>",Beebop and Doobert should start a band 12/10 would listen,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
707,785515384317313025,NaN,NaN,2016-10-10 16:20:36 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","Today, 10/10, should be National Dog Rates Day",NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
1445,696518437233913856,NaN,NaN,2016-02-08 02:18:30 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Oh my god 10/10 for every little hot dog pupper,NaN,NaN,NaN,NaN,10,10,None,None,None,pupper,None

In [47]:
# Change dataype of tweet_id
twitter_archive['in_reply_to_status_id'].count() / len(twitter_archive)

0.033106960950764007

In [48]:
twitter_archive.shape

(2356, 17)

In [49]:
# Using the describe method
twitter_archive.describe()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,retweeted_status_id,retweeted_status_user_id,rating_numerator,rating_denominator
count,2.356000e+03,7.800000e+01,7.800000e+01,1.810000e+02,1.810000e+02,2356.000000,2356.000000
mean,7.427716e+17,7.455079e+17,2.014171e+16,7.720400e+17,1.241698e+16,13.126486,10.455433
std,6.856705e+16,7.582492e+16,1.252797e+17,6.236928e+16,9.599254e+16,45.876648,6.745237
min,6.660209e+17,6.658147e+17,1.185634e+07,6.661041e+17,7.832140e+05,0.000000,0.000000
25%,6.783989e+17,6.757419e+17,3.086374e+08,7.186315e+17,4.196984e+09,10.000000,10.000000
50%,7.196279e+17,7.038708e+17,4.196984e+09,7.804657e+17,4.196984e+09,11.000000,10.000000
75%,7.993373e+17,8.257804e+17,4.196984e+09,8.203146e+17,4.196984e+09,12.000000,10.000000
max,8.924206e+17,8.862664e+17,8.405479e+17,8.874740e+17,7.874618e+17,1776.000000,170.000000

In [50]:
# Check rating numerators and denominators 
twitter_archive.nsmallest(10, 'rating_numerator')[['text', 'rating_numerator', 'rating_denominator']]

,text,rating_numerator,rating_denominator
315,When you're so blinded by your systematic plagiarism that you forget what day it is. 0/10 https://t.co/YbEJPkg4Ag,0,10
1016,"PUPDATE: can't see any. Even if I could, I couldn't reach them to pet. 0/10 much disappointment https://t.co/c7WXaB2nqX",0,10
605,RT @dog_rates: Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10 https://t.co/…,1,10
1446,After reading the comments I may have overestimated this pup. Downgraded to a 1/10. Please forgive me,1,10
1869,What kind of person sends in a picture without a dog in it? 1/10 just because that's a nice table https://t.co/RDXCfk8hK0,1,10
1940,The millennials have spoken and we've decided to immediately demote to a 1/10. Thank you,1,10
2038,After 22 minutes of careful deliberation this dog is being demoted to a 1/10. The longer you look at him the more terrifying he becomes,1,10
2091,Flamboyant pup here. Probably poisonous. Won't eat kibble. Doesn't bark. Slow af. Petting doesn't look fun. 1/10 https://t.co/jxukeh2BeO,1,10
2261,Never seen dog like this. Breathes heavy. Tilts head in a pattern. No bark. Shitty at fetch. Not even cordless. 1/10 https://t.co/i9iSGNn3fx,1,10
2335,This is an Albanian 3 1/2 legged Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 https://t.co/d9NcXFKwLv,1,2

In [51]:
twitter_archive.nlargest(10, 'rating_numerator')[['text', 'rating_numerator', 'rating_denominator']]

,text,rating_numerator,rating_denominator
979,This is Atticus. He's quite simply America af. 1776/10 https://t.co/GRXwMxLBkh,1776,10
313,"@jonnysun @Lin_Manuel ok jomny I know you're excited but 960/00 isn't a valid rating, 13/10 is tho",960,0
189,"@s8n You tried very hard to portray this good boy as not so good, but you have ultimately failed. His goodness shines through. 666/10",666,10
188,@dhmontgomery We also gave snoop dogg a 420/10 but I think that predated your research,420,10
2074,After so many requests... here you go.\n\nGood dogg. 420/10 https://t.co/yfAAo1gdeY,420,10
1120,Say hello to this unbelievably well behaved squad of doggos. 204/170 would try to pet all at once https://t.co/yGQI3He3xv,204,170
290,@markhoppus 182/10,182,10
902,Why does this never happen at my front door... 165/150 https://t.co/HmwrdfEfUE,165,150
1779,IT'S PUPPERGEDDON. Total of 144/120 ...I think https://t.co/ZanVtAtvIq,144,120
1634,"Two sneaky puppers were not initially seen, moving the rating to 143/130. Please forgive us. Thank you https://t.co/kRK51Y5ac3",143,130

In [52]:
twitter_archive.nsmallest(10, 'rating_denominator')[['text', 'rating_numerator', 'rating_denominator']]

,text,rating_numerator,rating_denominator
313,"@jonnysun @Lin_Manuel ok jomny I know you're excited but 960/00 isn't a valid rating, 13/10 is tho",960,0
2335,This is an Albanian 3 1/2 legged Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 https://t.co/d9NcXFKwLv,1,2
516,Meet Sam. She smiles 24/7 &amp; secretly aspires to be a reindeer. \nKeep Sam smiling by clicking and sharing this link:\nhttps://t.co/98tB8y7y7t https://t.co/LouL5vdvxx,24,7
0,This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU,13,10
1,"This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV",13,10
2,This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB,12,10
3,This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD36da7qLQ,13,10
4,"This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek https://t.co/AtUZn91f7f",12,10
5,Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek https://t.co/kQ04fDDRmh,13,10
6,Meet Jax. He enjoys ice cream so much he gets nervous around it. 13/10 help Jax enjoy more things by clicking below\n\nhttps://t.co/Zr4hWfAs1H https://t.co/tVJBRMnhxl,13,10

In [53]:
twitter_archive.nlargest(10, 'rating_denominator')[['text', 'rating_numerator', 'rating_denominator']]

,text,rating_numerator,rating_denominator
1120,Say hello to this unbelievably well behaved squad of doggos. 204/170 would try to pet all at once https://t.co/yGQI3He3xv,204,170
902,Why does this never happen at my front door... 165/150 https://t.co/HmwrdfEfUE,165,150
1634,"Two sneaky puppers were not initially seen, moving the rating to 143/130. Please forgive us. Thank you https://t.co/kRK51Y5ac3",143,130
1779,IT'S PUPPERGEDDON. Total of 144/120 ...I think https://t.co/ZanVtAtvIq,144,120
1635,Someone help the girl is being mugged. Several are distracting her while two steal her shoes. Clever puppers 121/110 https://t.co/1zfnTJLt55,121,110
1228,Happy Saturday here's 9 puppers on a bench. 99/90 good work everybody https://t.co/mpvaVxKmc1,99,90
1254,Here's a brigade of puppers. All look very prepared for whatever happens next. 80/80 https://t.co/0eb7R1Om12,80,80
1843,Here we have an entire platoon of puppers. Total score: 88/80 would pet all at once https://t.co/y93p6FLvVw,88,80
433,The floofs have been released I repeat the floofs have been released. 84/70 https://t.co/NIYC820tmd,84,70
1202,This is Bluebert. He just saw that both #FinalFur match ups are split 50/50. Amazed af. 11/10 https://t.co/Kky1DPG4iq,50,50

In [54]:
# In the above four DataFrames we can see that extreme ratings in the rating_numerator and rating_denominator 
# columns are largely in line with the twitter text, so our above hypothesis is not true. 
# But if we check i.e. the tweet in index 313 (the first tweet in the third DataFrame) or the tweet in 
# index 2335 (in the first DataFrame the last tweet), we can see that the first ratio found in text 
# was used to fill the rating numerator and denominator which is clearly not an optimal procedure as some 
# tweets seem to have more than one ratio in their body text. So we need to fix this.
# Using the sample method in order to identify any other remaining issues:
twitter_archive.sample(5)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
1829,676237365392908289,NaN,NaN,2015-12-14 03:08:46 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Say hello to Winston. He has no respect for the system. Much rebellion. I think that's a palm tree... nice. 8/10 https://t.co/dOLQddhXLZ,NaN,NaN,NaN,https://twitter.com/dog_rates/status/676237365392908289/photo/1,8,10,Winston,None,None,None,None
1285,708469915515297792,NaN,NaN,2016-03-12 01:49:25 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Bobble. He's a Croatian Galifianakis. Hears everything within 400 miles. 11/10 would snug diligently https://t.co/VwDc6PTDzk,NaN,NaN,NaN,https://twitter.com/dog_rates/status/708469915515297792/photo/1,11,10,Bobble,None,None,None,None
292,838083903487373313,NaN,NaN,2017-03-04 17:49:08 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Daisy. She's puppears to be rare as all h*ck. Only seven like her currently domesticated. 13/10 pettable af https://t.co/meUc8jufAO,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/838083903487373313/photo/1,https://twitter.com/dog_rates/status/838083903487373313/photo/1",13,10,Daisy,None,None,None,None
369,828650029636317184,NaN,NaN,2017-02-06 17:02:17 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","Occasionally, we're sent fantastic stories. This is one of them. 14/10 for Grace https://t.co/bZ4axuH6OK",NaN,NaN,NaN,"https://twitter.com/dog_rates/status/828650029636317184/photo/1,https://twitter.com/dog_rates/status/828650029636317184/photo/1,https://twitter.com/dog_rates/status/828650029636317184/photo/1",14,10,one,None,None,None,None
1810,676821958043033607,NaN,NaN,2015-12-15 17:51:44 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Finally some constructive political change in this country. 11/10 https://t.co/mvQaETHVSb,NaN,NaN,NaN,"https://twitter.com/dog_rates/status/676821958043033607/photo/1,https://twitter.com/dog_rates/status/676821958043033607/photo/1",11,10,None,None,None,None,None

In [55]:
#Split the timestamp column in two columns: date and time. 
# Also the source column contains url followed by text, which needs to be cleaned
# Lastly, at the end of each tweet the url of the tweet is present and should be cleaned

Quality

twitter_archive table

1.Retweets present in the DataFrame (we only want original tweets with images)

2.Columns relevant to retweets needs to be dropped (we only want original tweets with images). Replies related columns not really needed.

3.Erroneous datatype for tweet_id

4.Erroneous rating_nominator and rating_denominator values

5.Clean the url from the tweet text

Tidiness

twitter_archive table

1.The expanded_urls column contains in some cells multiple urls that should be cleaned.

2.Source column data contains html code that should be cleaned.

3.Four variables (doggo, floofer, pupper, puppo) should be merged in one column

4.Timestamp should be split into date and time

# 2)image_predictions

In [56]:
# Visualizing image_predictions DataFrame and assessing it.
image_predictions

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True
5,666050758794694657,https://pbs.twimg.com/media/CT5Jof1WUAEuVxN.jpg,1,Bernese_mountain_dog,0.651137,True,English_springer,0.263788,True,Greater_Swiss_Mountain_dog,0.016199,True
6,666051853826850816,https://pbs.twimg.com/media/CT5KoJ1WoAAJash.jpg,1,box_turtle,0.933012,False,mud_turtle,0.045885,False,terrapin,0.017885,False
7,666055525042405380,https://pbs.twimg.com/media/CT5N9tpXIAAifs1.jpg,1,chow,0.692517,True,Tibetan_mastiff,0.058279,True,fur_coat,0.054449,False
8,666057090499244032,https://pbs.twimg.com/media/CT5PY90WoAAQGLo.jpg,1,shopping_cart,0.962465,False,shopping_basket,0.014594,False,golden_retriever,0.007959,True
9,666058600524156928,https://pbs.twimg.com/media/CT5Qw94XAAA_2dP.jpg,1,miniature_poodle,0.201493,True,komondor,0.192305,True,soft-coated_wheaten_terrier,0.082086,True
10,666063827256086533,https://pbs.twimg.com/media/CT5Vg_wXIAAXfnj.jpg,1,golden_retriever,0.775930,True,Tibetan_mastiff,0.093718,True,Labrador_retriever,0.072427,True
11,666071193221509120,https://pbs.twimg.com/media/CT5cN_3WEAAlOoZ.jpg,1,Gordon_setter,0.503672,True,Yorkshire_terrier,0.174201,True,Pekinese,0.109454,True
12,666073100786774016,https://pbs.twimg.com/media/CT5d9DZXAAALcwe.jpg,1,Walker_hound,0.260857,True,English_foxhound,0.175382,True,Ibizan_hound,0.097471,True
13,666082916733198337,https://pbs.twimg.com/media/CT5m4VGWEAAtKc8.jpg,1,pug,0.489814,True,bull_mastiff,0.404722,True,French_bulldog,0.048960,True
14,666094000022159362,https://pbs.twimg.com/media/CT5w9gUW4AAsBNN.jpg,1,bloodhound,0.195217,True,German_shepherd,0.078260,True,malinois,0.075628,True
15,666099513787052032,https://pbs.twimg.com/media/CT51-JJUEAA6hV8.jpg,1,Lhasa,0.582330,True,Shih-Tzu,0.166192,True,Dandie_Dinmont,0.089688,True
16,666102155909144576,https://pbs.twimg.com/media/CT54YGiWUAEZnoK.jpg,1,English_setter,0.298617,True,Newfoundland,0.149842,True,borzoi,0.133649,True
17,666104133288665088,https://pbs.twimg.com/media/CT56LSZWoAAlJj2.jpg,1,hen,0.965932,False,cock,0.033919,False,partridge,0.000052,False
18,666268910803644416,https://pbs.twimg.com/media/CT8QCd1WEAADXws.jpg,1,desktop_computer,0.086502,False,desk,0.085547,False,bookcase,0.079480,False
19,666273097616637952,https://pbs.twimg.com/media/CT8T1mtUwAA3aqm.jpg,1,Italian_greyhound,0.176053,True,toy_terrier,0.111884,True,basenji,0.111152,True
20,666287406224695296,https://pbs.twimg.com/media/CT8g3BpUEAAuFjg.jpg,1,Maltese_dog,0.857531,True,toy_poodle,0.063064,True,miniature_poodle,0.025581,True
21,666293911632134144,https://pbs.twimg.com/media/CT8mx7KW4AEQu8N.jpg,1,three-toed_sloth,0.914671,False,otter,0.015250,False,great_grey_owl,0.013207,False
22,666337882303524864,https://pbs.twimg.com/media/CT9OwFIWEAMuRje.jpg,1,ox,0.416669,False,Newfoundland,0.278407,True,groenendael,0.102643,True
23,666345417576210432,https://pbs.twimg.com/media/CT9Vn7PWoAA_ZCM.jpg,1,golden_retriever,0.858744,True,Chesapeake_Bay_retriever,0.054787,True,Labrador_retriever,0.014241,True
24,666353288456101888,https://pbs.twimg.com/media/CT9cx0tUEAAhNN_.jpg,1,malamute,0.336874,True,Siberian_husky,0.147655,True,Eskimo_dog,0.093412,True
25,666362758909284353,https://pbs.twimg.com/media/CT9lXGsUcAAyUFt.jpg,1,guinea_pig,0.996496,False,skunk,0.002402,False,hamster,0.000461,False
26,666373753744588802,https://pbs.twimg.com/media/CT9vZEYWUAAlZ05.jpg,1,soft-coated_wheaten_terrier,0.326467,True,Afghan_hound,0.259551,True,briard,0.206803,True
27,666396247373291520,https://pbs.twimg.com/media/CT-D2ZHWIAA3gK1.jpg,1,Chihuahua,0.978108,True,toy_terrier,0.009397,True,papillon,0.004577,True
28,666407126856765440,https://pbs.twimg.com/media/CT-NvwmW4AAugGZ.jpg,1,black-and-tan_coonhound,0.529139,True,bloodhound,0.244220,True,flat-coated_retriever,0.173810,True
29,666411507551481857,https://pbs.twimg.com/media/CT-RugiWIAELEaq.jpg,1,coho,0.404640,False,barracouta,0.271485,False,gar,0.189945,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2045,886366144734445568,https://pbs.twimg.com/media/DE0BTnQUwAApKEH.jpg,1,French_bulldog,0.999201,True,Chihuahua,0.000361,True,Boston_bull,0.000076,True
2046,886680336477933568,https://pbs.twimg.com/media/DE4fEDzWAAAyHMM.jpg,1,convertible,0.738995,False,sports_car,0.139952,False,car_wheel,0.044173,False
2047,886736880519319552,https://pbs.twimg.com/media/DE5Se8FXcAAJFx4.jpg,1,kuvasz,0.309706,True,Great_Pyrenees,0.186136,True,Dandie_Dinmont,0.086346,True
2048,886983233522544640,https://pbs.twimg.com/media/DE8yicJW0AAAvBJ.jpg,2,Chihuahua,0.793469,True,toy_terrier,0.143528,True,can_opener,0.032253,False
2049,887101392804085760,https://pbs.twimg.com/media/DE-eAq6UwAA-jaE.jpg,1,Samoyed,0.733942,True,Eskimo_dog,0.035029,True,Staffordshire_bullterrier,0.029705,True
2050,887343217045368832,https://pbs.twimg.com/ext_tw_video_thumb/887343120832229379/pu/img/6HSuFrW1lzI_9Mht.jpg,1,Mexican_hairless,0.330741,True,sea_lion,0.275645,False,Weimaraner,0.134203,True
2051,887473957103951883,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,2,Pembroke,0.809197,True,Rhodesian_ridgeback,0.054950,True,beagle,0.038915,True
2052,887517139158093824,https://pbs.twimg.com/ext_tw_video_thumb/887517108413886465/pu/img/WanJKwssZj4VJvL9.jpg,1,limousine,0.130432,False,tow_truck,0.029175,False,shopping_cart,0.026321,False
2053,887705289381826560,https://pbs.twimg.com/media/DFHDQBbXgAEqY7t.jpg,1,basset,0.821664,True,redbone,0.087582,True,Weimaraner,0.026236,True
2054,888078434458587136,https://pbs.twimg.com/media/DFMWn56WsAAkA7B.jpg,1,French_bulldog,0.995026,True,pug,0.000932,True,bull_mastiff,0.000903,True
2055,888202515573088257,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,2,Pembroke,0.809197,True,Rhodesian_ridgeback,0.054950,True,beagle,0.038915,True
2056,888554962724278272,https://pbs.twimg.com/media/DFTH_O-UQAACu20.jpg,3,Siberian_husky,0.700377,True,Eskimo_dog,0.166511,True,malamute,0.111411,True
2057,888804989199671297,https://pbs.twimg.com/media/DFWra-3VYAA2piG.jpg,1,golden_retriever,0.469760,True,Labrador_retriever,0.184172,True,English_setter,0.073482,True
2058,888917238123831296,https://pbs.twimg.com/media/DFYRgsOUQAARGhO.jpg,1,golden_retriever,0.714719,True,Tibetan_mastiff,0.120184,True,Labrador_retriever,0.105506,True
2059,889278841981685760,https://pbs.twimg.com/ext_tw_video_thumb/889278779352338437/pu/img/VlbFB3v8H8VwzVNY.jpg,1,whippet,0.626152,True,borzoi,0.194742,True,Saluki,0.027351,True
2060,889531135344209921,https://pbs.twimg.com/media/DFg_2PVW0AEHN3p.jpg,1,golden_retriever,0.953442,True,Labrador_retriever,0.013834,True,redbone,0.007958,True
2061,889638837579907072,https://pbs.twimg.com/media/DFihzFfXsAYGDPR.jpg,1,French_bulldog,0.991650,True,boxer,0.002129,True,Staffordshire_bullterrier,0.001498,True
2062,889665388333682689,https://pbs.twimg.com/media/DFi579UWsAAatzw.jpg,1,Pembroke,0.966327,True,Cardigan,0.027356,True,basenji,0.004633,True
2063,889880896479866881,https://pbs.twimg.com/media/DFl99B1WsAITKsg.jpg,1,French_bulldog,0.377417,True,Labrador_retriever,0.151317,True,muzzle,0.082981,False
2064,890006608113172480,https://pbs.twimg.com/media/DFnwSY4WAAAMliS.jpg,1,Samoyed,0.957979,True,Pomeranian,0.013884,True,chow,0.008167,True
2065,890240255349198849,https://pbs.twimg.com/media/DFrEyVuW0AAO3t9.jpg,1,Pembroke,0.511319,True,Cardigan,0.451038,True,Chihuahua,0.029248,True
2066,890609185150312448,https://pbs.twimg.com/media/DFwUU__XcAEpyXI.jpg,1,Irish_terrier,0.487574,True,Irish_setter,0.193054,True,Chesapeake_Bay_retriever,0.118184,True
2067,890729181411237888,https://pbs.twimg.com/media/DFyBahAVwAAhUTd.jpg,2,Pomeranian,0.566142,True,Eskimo_dog,0.178406,True,Pembroke,0.076507,True
2068,890971913173991426,https://pbs.twimg.com/media/DF1eOmZXUAALUcq.jpg,1,Appenzeller,0.341703,True,Border_collie,0.199287,True,ice_lolly,0.193548,False
2069,891087950875897856,https://pbs.twimg.com/media/DF3HwyEWsAABqE6.jpg,1,Chesapeake_Bay_retriever,0.425595,True,Irish_terrier,0.116317,True,Indian_elephant,0.076902,False
2070,891327558926688256,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True
2071,891689557279858688,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False
2072,891815181378084864,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True
2073,892177421306343426,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True
2074,892420643555336193,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False

In [57]:
# Capitalize all breed names across columns
# Several columns have non descriptive names (p1, p1_conf, p1_dog, p2, 
# p2_conf, p2_dog, p3, p3_conf, p3_dog)
image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

In [58]:
#Change tweet_id datatype.
image_predictions.describe()

           tweet_id      img_num      p1_conf       p2_conf       p3_conf
count  2.075000e+03  2075.000000  2075.000000  2.075000e+03  2.075000e+03
mean   7.384514e+17     1.203855     0.594548  1.345886e-01  6.032417e-02
std    6.785203e+16     0.561875     0.271174  1.006657e-01  5.090593e-02
min    6.660209e+17     1.000000     0.044333  1.011300e-08  1.740170e-10
25%    6.764835e+17     1.000000     0.364412  5.388625e-02  1.622240e-02
50%    7.119988e+17     1.000000     0.588230  1.181810e-01  4.944380e-02
75%    7.932034e+17     1.000000     0.843855  1.955655e-01  9.180755e-02
max    8.924206e+17     4.000000     1.000000  4.880140e-01  2.734190e-01

In [59]:
image_predictions.sample(5)

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
1543,791406955684368384,https://pbs.twimg.com/media/CvukbEkWAAAV-69.jpg,4,Pembroke,0.972629,True,Cardigan,0.027026,True,basenji,0.000153,True
1444,775733305207554048,https://pbs.twimg.com/media/CsP1UvaW8AExVSA.jpg,1,long-horned_beetle,0.613852,False,ox,0.029473,False,rhinoceros_beetle,0.027806,False
629,680913438424612864,https://pbs.twimg.com/media/CXMXKKHUMAA1QN3.jpg,1,Pomeranian,0.615678,True,golden_retriever,0.126455,True,Chihuahua,0.087184,True
619,680440374763077632,https://pbs.twimg.com/ext_tw_video_thumb/680440290977693696/pu/img/B900g7b-n-zhnwi5.jpg,1,space_heater,0.920367,False,radiator,0.049933,False,electric_fan,0.006719,False
529,676811746707918848,https://pbs.twimg.com/media/CWSEsO9WwAAX-fZ.jpg,1,Chihuahua,0.440916,True,Pomeranian,0.345806,True,cocker_spaniel,0.060331,True

Quality

image_predictions table

1.Erroneous datatype for tweet_id.

2.Lowercase dog breed names

3.Non-descriptive column names for several variable

# 3)tweet_json

In [60]:
#check downloaded data from the Twitter API
tweet_json

,tweet_id,favorite_count,retweet_count,created_at,source,retweeted_status,url
0,886054160059072513,0,104,Sat Jul 15 02:45:48 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
1,885311592912609280,0,18595,Thu Jul 13 01:35:06 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
2,879130579576475649,0,6857,Mon Jun 26 00:13:58 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
3,878404777348136964,0,1299,Sat Jun 24 00:09:53 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
4,878316110768087041,0,6674,Fri Jun 23 18:17:33 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
5,877611172832227328,0,81,Wed Jun 21 19:36:23 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
6,874434818259525634,0,14866,Tue Jun 13 01:14:41 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
7,873337748698140672,0,1601,Sat Jun 10 00:35:19 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
8,871166179821445120,0,5770,Sun Jun 04 00:46:17 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
9,868639477480148993,0,2144,Sun May 28 01:26:04 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
10,867072653475098625,0,130,Tue May 23 17:40:04 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
11,866094527597207552,0,8616,Sun May 21 00:53:21 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
12,863471782782697472,0,2556,Sat May 13 19:11:30 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
13,860981674716409858,0,2245,Sat May 06 22:16:42 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
14,860924035999428608,0,846,Sat May 06 18:27:40 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
15,860177593139703809,0,32142,Thu May 04 17:01:34 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
16,858860390427611136,0,8481,Mon May 01 01:47:28 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
17,857062103051644929,0,178,Wed Apr 26 02:41:43 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
18,856602993587888130,0,11211,Mon Apr 24 20:17:23 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
19,856330835276025856,0,712,Mon Apr 24 02:15:55 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
20,855245323840757760,0,6303,Fri Apr 21 02:22:29 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
21,855138241867124737,0,48,Thu Apr 20 19:16:59 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
22,852936405516943360,0,2156,Fri Apr 14 17:27:40 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
23,851953902622658560,0,10300,Wed Apr 12 00:23:33 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
24,851861385021730816,0,23,Tue Apr 11 18:15:55 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
25,849668094696017920,0,5326,Wed Apr 05 17:00:34 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
26,847978865427394560,0,3508,Sat Apr 01 01:08:10 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
27,847971574464610304,0,463,Sat Apr 01 00:39:12 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
28,845098359547420673,0,8300,Fri Mar 24 02:22:04 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
29,841833993020538882,0,16736,Wed Mar 15 02:10:39 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
...,...,...,...,...,...,...,...
138,776249906839351296,0,10220,Thu Sep 15 02:42:54 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
139,775898661951791106,0,17236,Wed Sep 14 03:27:11 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
140,773336787167145985,0,5673,Wed Sep 07 01:47:12 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
141,772615324260794368,0,3741,Mon Sep 05 02:00:22 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
142,771171053431250945,0,8398,Thu Sep 01 02:21:21 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
143,771004394259247104,0,245,Wed Aug 31 15:19:06 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
144,770093767776997377,0,3374,Mon Aug 29 03:00:36 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
145,769335591808995329,0,8520,Sat Aug 27 00:47:53 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
146,768909767477751808,0,3001,Thu Aug 25 20:35:48 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
147,768554158521745409,0,6462,Wed Aug 24 21:02:45 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
148,766864461642756096,0,6283,Sat Aug 20 05:08:29 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
149,766078092750233600,0,2873,Thu Aug 18 01:03:45 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
150,763167063695355904,0,3346,Wed Aug 10 00:16:21 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
151,761750502866649088,0,4372,Sat Aug 06 02:27:27 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
152,761371037149827077,0,19811,Fri Aug 05 01:19:35 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
153,760153949710192640,0,36,Mon Aug 01 16:43:19 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
154,759566828574212096,0,23390,Sun Jul 31 01:50:18 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
155,759159934323924993,0,1296,Fri Jul 29 22:53:27 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
156,757729163776290825,0,8952,Tue Jul 26 00:08:05 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
157,757597904299253760,0,322,Mon Jul 25 15:26:30 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
158,754874841593970688,0,8835,Mon Jul 18 03:06:01 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
159,753298634498793472,0,6366,Wed Jul 13 18:42:44 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
160,752701944171524096,0,3175,Tue Jul 12 03:11:42 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
161,752309394570878976,0,18358,Mon Jul 11 01:11:51 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
162,747242308580548608,0,3158,Mon Jun 27 01:37:04 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
163,746521445350707200,0,1075,Sat Jun 25 01:52:36 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
164,743835915802583040,0,2289,Fri Jun 17 16:01:16 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
165,711998809858043904,0,136,Mon Mar 21 19:31:59 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
166,667550904950915073,0,35,Fri Nov 20 03:51:52 +0000 2015,Twitter Web Client,This is a retweet,This is a retweet
167,667550882905632768,0,33,Fri Nov 20 03:51:47 +0000 2015,Twitter Web Client,This is a retweet,This is a retweet

In [61]:
#Fetch the favorite_count and retweet_count columns
#add them to the twitter_archive DataFrame. So, we need to update the tidiness 
#issues of the twitter-archive table. We will also use the source column to update 
#the source column of the twitter-archive table. We have already documented the need 
#for cleaning the source column in the twitter-archive assessment.

In [62]:
# Check if retweets in the twitter-archive DataFrame are identified as
# retweets in the tweet_json DataFrame
tw_arch_retw = twitter_archive[twitter_archive['retweeted_status_id'].notnull()]['tweet_id'].tolist()
tweet_json_retw = tweet_json[tweet_json['retweeted_status'] == "This is a retweet" ]['tweet_id'].tolist()
tweet_json['retweeted_status'].value_counts()

This is a retweet    168
Name: retweeted_status, dtype: int64

In [63]:
# Checking datatypes of newly created lists:
print(type(tw_arch_retw[0]))
print(type(tweet_json_retw[0]))

<class 'int'>
<class 'str'>

In [64]:
# Converting list of strs to list of int in order to check for common elements
tweet_json_retw = list(map(int, tweet_json_retw))

In [65]:
# Count the number of common elements
len(list(set(tw_arch_retw).intersection(tweet_json_retw)))

168

In [66]:
len(tw_arch_retw)

181

In [67]:
#Use the retweeted_status_id column in the twitter-archive DataFrame
#to exclude retweets from the dataset
#7 retweets that weren't found in the Twitter API
#Find the urls of the fours tweets that wasn't replies:
tweet_json[tweet_json['tweet_id'].isin(list(map(str, my_non_url_non_replies_ids)))]

,tweet_id,favorite_count,retweet_count,created_at,source,retweeted_status,url
19,856330835276025856,0,712,Mon Apr 24 02:15:55 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet

In [68]:
# Not even in the Twitter API the urls of these tweets could be found
image_predictions[image_predictions['tweet_id'].isin(list(map(str, my_non_url_non_replies_ids)))]

Empty DataFrame
Columns: [tweet_id, jpg_url, img_num, p1, p1_conf, p1_dog, p2, p2_conf, p2_dog, p3, p3_conf, p3_dog]
Index: []

In [69]:
#No image predictions so drop all such datsets
tweet_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 7 columns):
tweet_id            168 non-null object
favorite_count      168 non-null int64
retweet_count       168 non-null int64
created_at          168 non-null object
source              168 non-null object
retweeted_status    168 non-null object
url                 168 non-null object
dtypes: int64(2), object(5)
memory usage: 9.3+ KB

In [70]:
tweet_json.describe()

       favorite_count  retweet_count
count           168.0     168.000000
mean              0.0    6824.357143
std               0.0    6493.905029
min               0.0      23.000000
25%               0.0    2606.000000
50%               0.0    5550.500000
75%               0.0    8544.000000
max               0.0   40835.000000

In [71]:
tweet_json.sample(5)

,tweet_id,favorite_count,retweet_count,created_at,source,retweeted_status,url
91,800443802682937345,0,4849,Sun Nov 20 21:00:48 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
153,760153949710192640,0,36,Mon Aug 01 16:43:19 +0000 2016,Twitter for iPhone,This is a retweet,This is a retweet
7,873337748698140672,0,1601,Sat Jun 10 00:35:19 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
5,877611172832227328,0,81,Wed Jun 21 19:36:23 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet
43,832769181346996225,0,41,Sat Feb 18 01:50:19 +0000 2017,Twitter for iPhone,This is a retweet,This is a retweet

Tidiness

twitter-archive table

Missing columns: favorite_count and retweet_count

To summarise the twitter_archive table has multiple quality and tidyness issue.

# Clean

Cleaning of the dataset starts here...

In [72]:
#Clean DataFrames based on the issues we found in 
#the assessment part of this wrangling project
#Firstly,make a copy of all 3 DataFrames:
twitter_archive_clean = twitter_archive.copy()
image_predictions_clean = image_predictions.copy()
tweet_json_clean = tweet_json.copy()

Quality issues

twitter-archive table

Retweets present in the dataset (we only want original tweets with images)

Define

Use the 'retweed_status_id' to drop retweets. Then use the 'tweet_id' from the image_predictions_clean DataFrame to keep only tweets with images.

Code

In [73]:
# Use separated retweed_status_id values in a list named as tw_arch_retw. 
# Use it to drop the rows containing retweets:
twitter_archive_clean = twitter_archive_clean[~twitter_archive_clean.tweet_id.isin(tw_arch_retw)]
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2175 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2175 non-null object
source                        2175 non-null object
text                          2175 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2117 non-null object
rating_numerator              2175 non-null int64
rating_denominator            2175 non-null int64
name                          2175 non-null object
doggo                         2175 non-null object
floofer                       2175 non-null object
pupper                        2175 non-null object
puppo                         2175 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 305.9+ KB

In [74]:
# So we are left with 2175 original tweets. Now it's time to see which 
# of those tweets have image predictions in the image_prediction DataFrame.
# Separating image prediction ids
image_pred_ids = image_predictions_clean['tweet_id'].tolist()

In [75]:
# Seperating original tweet ids
twitter_archive_clean_ids = twitter_archive_clean['tweet_id'].tolist()

In [76]:
# Checking datatypes of newly created lists:
print(type(image_pred_ids[0]))
print(type(twitter_archive_clean_ids[0]))

<class 'int'>
<class 'int'>

In [77]:
# Count the number of common elements between the two lists:
print(len(list(set(image_pred_ids).intersection(twitter_archive_clean_ids))))

1994

In [78]:
# So there are 1994 original tweets that have image predictions.
# Saving the list of those tweets:
original_tweets_with_image_prediction_ids = list(set(image_pred_ids).intersection(twitter_archive_clean_ids))

In [79]:
# Keep only original tweets with image predictions
twitter_archive_clean = twitter_archive_clean[twitter_archive_clean.tweet_id.isin(original_tweets_with_image_prediction_ids)]

Test

In [80]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      1994 non-null int64
in_reply_to_status_id         23 non-null float64
in_reply_to_user_id           23 non-null float64
timestamp                     1994 non-null object
source                        1994 non-null object
text                          1994 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 1994 non-null object
rating_numerator              1994 non-null int64
rating_denominator            1994 non-null int64
name                          1994 non-null object
doggo                         1994 non-null object
floofer                       1994 non-null object
pupper                        1994 non-null object
puppo                         1994 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 280.4+ KB

Dropping Retweets (we only want original tweets with images). Replies related columns not really needed.

Define

Use pandas.DataFrame.drop to get rid of columns related to retweets and replies.

Test

In [81]:
twitter_archive_clean = twitter_archive_clean.drop(['retweeted_status_id', 
                                                    'retweeted_status_user_id', 
                                                    'retweeted_status_timestamp', 
                                                    'in_reply_to_status_id', 
                                                    'in_reply_to_user_id'],
                                                   axis=1)

In [82]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              1994 non-null int64
timestamp             1994 non-null object
source                1994 non-null object
text                  1994 non-null object
expanded_urls         1994 non-null object
rating_numerator      1994 non-null int64
rating_denominator    1994 non-null int64
name                  1994 non-null object
doggo                 1994 non-null object
floofer               1994 non-null object
pupper                1994 non-null object
puppo                 1994 non-null object
dtypes: int64(3), object(9)
memory usage: 202.5+ KB

Erroneous datatype for tweet_id

Define

Convert 'tweed_id' column to string dataype

In [83]:
twitter_archive_clean['tweet_id'] = twitter_archive_clean['tweet_id'].astype('str')

Test

In [84]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1994 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              1994 non-null object
timestamp             1994 non-null object
source                1994 non-null object
text                  1994 non-null object
expanded_urls         1994 non-null object
rating_numerator      1994 non-null int64
rating_denominator    1994 non-null int64
name                  1994 non-null object
doggo                 1994 non-null object
floofer               1994 non-null object
pupper                1994 non-null object
puppo                 1994 non-null object
dtypes: int64(2), object(10)
memory usage: 202.5+ KB

Erroneous rating_nominator and rating_denominator values

Define

Create a new column that stores all ratios found in the 'text' column. Use it to drop tweets containing more than one ratio.

Code

In [85]:
#Create a list of all ratings found in each tweet:
saved_ratios = []
for my_index in twitter_archive_clean.index.tolist():
    ratio = re.findall(r'\d+/\d+', twitter_archive_clean.loc[my_index, 'text'])
    saved_ratios.append(ratio)

In [86]:
# Adding the list to our DataFrame
twitter_archive_clean['rating'] = saved_ratios

In [87]:
# Fetching the indexes of tweets that have more than one rating: 
indexes_of_double_ratios = []
for my_index in twitter_archive_clean.index.tolist():
    if len(twitter_archive_clean.loc[my_index, 'rating']) > 1:
        indexes_of_double_ratios.append(my_index)

In [88]:
# Printing these tweets:
twitter_archive_clean.loc[indexes_of_double_ratios, 
                          ['text', 'rating_numerator', 'rating_denominator',
                          'url', 'rating']]

,text,rating_numerator,rating_denominator,url,rating
766,"""Yep... just as I suspected. You're not flossing."" 12/10 and 11/10 for the pup not flossing https://t.co/SuXcI9B7pQ",12,10,NaN,"[12/10, 11/10]"
1007,This is Bookstore and Seaweed. Bookstore is tired and Seaweed is an asshole. 10/10 and 7/10 respectively https://t.co/eUGjGjjFVJ,10,10,NaN,"[10/10, 7/10]"
1068,"After so many requests, this is Bretagne. She was the last surviving 9/11 search dog, and our second ever 14/10. RIP https://t.co/XAVDNDaVgQ",9,11,NaN,"[9/11, 14/10]"
1165,Happy 4/20 from the squad! 13/10 for all https://t.co/eV1diwds8a,4,20,NaN,"[4/20, 13/10]"
1202,This is Bluebert. He just saw that both #FinalFur match ups are split 50/50. Amazed af. 11/10 https://t.co/Kky1DPG4iq,50,50,NaN,"[50/50, 11/10]"
1222,Meet Travis and Flurp. Travis is pretty chill but Flurp can't lie down properly. 10/10 &amp; 8/10\nget it together Flurp https://t.co/Akzl5ynMmE,10,10,NaN,"[10/10, 8/10]"
1359,This is Socks. That water pup w the super legs just splashed him. Socks did not appreciate that. 9/10 and 2/10 https://t.co/8rc5I22bBf,9,10,NaN,"[9/10, 2/10]"
1459,"This may be the greatest video I've ever been sent. 4/10 for Charles the puppy, 13/10 overall. (Vid by @stevenxx_) https://t.co/uaJmNgXR2P",4,10,NaN,"[4/10, 13/10]"
1465,Meet Oliviér. He takes killer selfies. Has a dog of his own. It leaps at random &amp; can't bark for shit. 10/10 &amp; 5/10 https://t.co/6NgsQJuSBJ,10,10,NaN,"[10/10, 5/10]"
1508,When bae says they can't go out but you see them with someone else that same night. 5/10 &amp; 10/10 for heartbroken pup https://t.co/aenk0KpoWM,5,10,NaN,"[5/10, 10/10]"
1525,This is Eriq. His friend just reminded him of last year's super bowl. Not cool friend\n10/10 for Eriq\n6/10 for friend https://t.co/PlEXTofdpf,10,10,NaN,"[10/10, 6/10]"
1538,Meet Fynn &amp; Taco. Fynn is an all-powerful leaf lord and Taco is in the wrong place at the wrong time. 11/10 &amp; 10/10 https://t.co/MuqHPvtL8c,11,10,NaN,"[11/10, 10/10]"
1662,This is Darrel. He just robbed a 7/11 and is in a high speed police chase. Was just spotted by the helicopter 10/10 https://t.co/7EsP8LmSp5,7,11,NaN,"[7/11, 10/10]"
1795,"Meet Tassy &amp; Bee. Tassy is pretty chill, but Bee is convinced the Ruffles are haunted. 10/10 &amp; 11/10 respectively https://t.co/fgORpmTN9C",10,10,NaN,"[10/10, 11/10]"
1832,These two pups just met and have instantly bonded. Spectacular scene. Mesmerizing af. 10/10 and 7/10 for blue dog https://t.co/gwryaJO4tC,10,10,NaN,"[10/10, 7/10]"
1897,Meet Rufio. He is unaware of the pink legless pupper wrapped around him. Might want to get that checked 10/10 &amp; 4/10 https://t.co/KNfLnYPmYh,10,10,NaN,"[10/10, 4/10]"
1901,Two gorgeous dogs here. Little waddling dog is a rebel. Refuses to look at camera. Must be a preteen. 5/10 &amp; 8/10 https://t.co/YPfw7oahbD,5,10,NaN,"[5/10, 8/10]"
1970,Meet Eve. She's a raging alcoholic 8/10 (would b 11/10 but pupper alcoholism is a tragic issue that I can't condone) https://t.co/U36HYQIijg,8,10,NaN,"[8/10, 11/10]"
2010,10/10 for dog. 7/10 for cat. 12/10 for human. Much skill. Would pet all https://t.co/uhx5gfpx5k,10,10,NaN,"[10/10, 7/10, 12/10]"
2064,Meet Holly. She's trying to teach small human-like pup about blocks but he's not paying attention smh. 11/10 &amp; 8/10 https://t.co/RcksaUrGNu,11,10,NaN,"[11/10, 8/10]"
2113,Meet Hank and Sully. Hank is very proud of the pumpkin they found and Sully doesn't give a shit. 11/10 and 8/10 https://t.co/cwoP1ftbrj,11,10,NaN,"[11/10, 8/10]"
2177,"Here we have Pancho and Peaches. Pancho is a Condoleezza Gryffindor, and Peaches is just an asshole. 10/10 &amp; 7/10 https://t.co/Lh1BsJrWPp",10,10,NaN,"[10/10, 7/10]"
2216,This is Spark. He's nervous. Other dog hasn't moved in a while. Won't come when called. Doesn't fetch well 8/10&amp;1/10 https://t.co/stEodX9Aba,8,10,NaN,"[8/10, 1/10]"
2263,"This is Kial. Kial is either wearing a cape, which would be rad, or flashing us, which would be rude. 10/10 or 4/10 https://t.co/8zcwIoiuqR",10,10,NaN,"[10/10, 4/10]"
2272,Two dogs in this one. Both are rare Jujitsu Pythagoreans. One slightly whiter than other. Long legs. 7/10 and 8/10 https://t.co/ITxxcc4v9y,7,10,NaN,"[7/10, 8/10]"
2306,These are Peruvian Feldspars. Their names are Cupit and Prencer. Both resemble Rand Paul. Sick outfits 10/10 &amp; 10/10 https://t.co/ZnEMHBsAs1,10,10,NaN,"[10/10, 10/10]"
2335,This is an Albanian 3 1/2 legged Episcopalian. Loves well-polished hardwood flooring. Penis on the collar. 9/10 https://t.co/d9NcXFKwLv,1,2,NaN,"[1/2, 9/10]"

In [89]:
len(indexes_of_double_ratios)

27

In [90]:
# There are only 27 tweets that have more than 1 ratio in their text.
# Most often the reason for having more than one rating is that the 
# image attached to the tweet has more than 1 animal depicted 
# (usually a second dog).
# As a consequence the rating_numerator and rating_denominator columns
# contain only the first encountered ratio in the tweet text which is 
# clearly not optimal. We must notice that for few tweets the added ratio is 
# not related to dog ratings (i.e a date). 
# If we try to classify these ratios as 'dog rating' or 'not dog rating' 
# the only noticeable pattern in the tweets is this one: when a ratio is 
# followed by the word 'and' or '&amp;' then followed by another ratio, 
# then these two ratios most likely refer to dog ratings. 
# Even if we did that, we should check one by one the remaining tweets. 
# Moreover, the fact that we need to store the added ratings in a new column, 
# thus creating columns almost full of NaNs (as only 27 tweets out of 1994 have 
# more than one rating), further leads us to the decision to entirely drop these 
# 27 tweets and work only with tweets that have only one rating.
# Dropping double ratio tweeets:
twitter_archive_clean = twitter_archive_clean[~twitter_archive_clean.index.isin(indexes_of_double_ratios)]

In [91]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 2355
Data columns (total 13 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
expanded_urls         1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
rating                1967 non-null object
dtypes: int64(2), object(11)
memory usage: 215.1+ KB

In [92]:
# We are left with 1967 tweets. Now it's time to drop the 'rating' column 
# that we created as we dont need it anymore:
twitter_archive_clean = twitter_archive_clean.drop('rating', axis=1)

Test

In [93]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 2355
Data columns (total 12 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
expanded_urls         1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
dtypes: int64(2), object(10)
memory usage: 199.8+ KB

In [94]:
twitter_archive_clean.sample(5)

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
981,749417653287129088,2016-07-03 01:41:06 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Finn. He's the most unphotogenic pupper of all time. 11/10 https://t.co/qvA2rCUl6v,"https://twitter.com/dog_rates/status/749417653287129088/photo/1,https://twitter.com/dog_rates/status/749417653287129088/photo/1,https://twitter.com/dog_rates/status/749417653287129088/photo/1,https://twitter.com/dog_rates/status/749417653287129088/photo/1",11,10,Finn,None,None,pupper,None
1978,672984142909456390,2015-12-05 03:41:37 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Very happy pup here. Always smiling. Loves his little leaf. Carries it everywhere with him. 9/10 https://t.co/81BCQAyvcs,https://twitter.com/dog_rates/status/672984142909456390/photo/1,9,10,None,None,None,None,None
1110,733822306246479872,2016-05-21 00:50:46 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Moose. He's a Polynesian Floofer. Dapper af. 10/10 would pet diligently https://t.co/mVfqRdppTL,https://twitter.com/dog_rates/status/733822306246479872/photo/1,10,10,Moose,None,floofer,None,None
1186,718540630683709445,2016-04-08 20:46:50 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Get you a pup that can do both. 10/10 https://t.co/zSbyvm62xZ,"https://twitter.com/dog_rates/status/718540630683709445/photo/1,https://twitter.com/dog_rates/status/718540630683709445/photo/1",10,10,None,None,None,None,None
650,792883833364439040,2016-10-31 00:20:11 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Bailey. She's rather h*ckin hype for Halloween tomorrow. Carved those pupkins herself. 12/10 https://t.co/v17mFm0Ftz,"https://twitter.com/dog_rates/status/792883833364439040/photo/1,https://twitter.com/dog_rates/status/792883833364439040/photo/1,https://twitter.com/dog_rates/status/792883833364439040/photo/1,https://twitter.com/dog_rates/status/792883833364439040/photo/1",12,10,Bailey,None,None,None,None

Clean the url from the tweet text

Define

Separate the url part of each tweet in the 'text' column and delete it.

Code

In [95]:
# This function takes as input a dataframe column, search for a specif word and deletes all text after it 
# including the word. The output is stored into a list.
def create_a_list_of_str_up_to_word(dataframe, column, word):
    my_list_of_texts = []
    for my_text in dataframe[column]:
        my_list_of_texts.append(my_text)
    all_cleaned_texts = []
    for my_text_2 in my_list_of_texts:
        cleaned_text = my_text_2[:my_text_2.find(word)-1]
        all_cleaned_texts.append(cleaned_text)
    return(all_cleaned_texts)

In [96]:
#Check the cleaned data
twitter_archive_clean['new_text'] = create_a_list_of_str_up_to_word(twitter_archive_clean, 'text', 'https')

In [97]:
twitter_archive_clean.loc[:, ['text', 'new_text']]

,text,new_text
0,This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10 https://t.co/MgUWQ76dJU,This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10
1,"This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10 https://t.co/0Xxu71qeIV","This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10"
2,This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10 https://t.co/wUnZnhtVJB,This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10
3,This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us https://t.co/tD36da7qLQ,This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us
4,"This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek https://t.co/AtUZn91f7f","This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek"
5,Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek https://t.co/kQ04fDDRmh,Here we have a majestic great white breaching off South Africa's coast. Absolutely h*ckin breathtaking. 13/10 (IG: tucker_marlo) #BarkWeek
6,Meet Jax. He enjoys ice cream so much he gets nervous around it. 13/10 help Jax enjoy more things by clicking below\n\nhttps://t.co/Zr4hWfAs1H https://t.co/tVJBRMnhxl,Meet Jax. He enjoys ice cream so much he gets nervous around it. 13/10 help Jax enjoy more things by clicking below\n
7,When you watch your owner call another dog a good boy but then they turn back to you and say you're a great boy. 13/10 https://t.co/v0nONBcwxq,When you watch your owner call another dog a good boy but then they turn back to you and say you're a great boy. 13/10
8,This is Zoey. She doesn't want to be one of the scary sharks. Just wants to be a snuggly pettable boatpet. 13/10 #BarkWeek https://t.co/9TwLuAGH0b,This is Zoey. She doesn't want to be one of the scary sharks. Just wants to be a snuggly pettable boatpet. 13/10 #BarkWeek
9,This is Cassie. She is a college pup. Studying international doggo communication and stick theory. 14/10 so elegant much sophisticate https://t.co/t1bfwz5S2A,This is Cassie. She is a college pup. Studying international doggo communication and stick theory. 14/10 so elegant much sophisticate
10,This is Koda. He is a South Australian deckshark. Deceptively deadly. Frighteningly majestic. 13/10 would risk a petting #BarkWeek https://t.co/dVPW0B0Mme,This is Koda. He is a South Australian deckshark. Deceptively deadly. Frighteningly majestic. 13/10 would risk a petting #BarkWeek
11,This is Bruno. He is a service shark. Only gets out of the water to assist you. 13/10 terrifyingly good boy https://t.co/u1XPQMl29g,This is Bruno. He is a service shark. Only gets out of the water to assist you. 13/10 terrifyingly good boy
12,Here's a puppo that seems to be on the fence about something haha no but seriously someone help her. 13/10 https://t.co/BxvuXk0UCm,Here's a puppo that seems to be on the fence about something haha no but seriously someone help her. 13/10
13,This is Ted. He does his best. Sometimes that's not enough. But it's ok. 12/10 would assist https://t.co/f8dEDcrKSR,This is Ted. He does his best. Sometimes that's not enough. But it's ok. 12/10 would assist
14,This is Stuart. He's sporting his favorite fanny pack. Secretly filled with bones only. 13/10 puppared puppo #BarkWeek https://t.co/y70o6h3isq,This is Stuart. He's sporting his favorite fanny pack. Secretly filled with bones only. 13/10 puppared puppo #BarkWeek
15,This is Oliver. You're witnessing one of his many brutal attacks. Seems to be playing with his victim. 13/10 fr*ckin frightening #BarkWeek https://t.co/WpHvrQedPb,This is Oliver. You're witnessing one of his many brutal attacks. Seems to be playing with his victim. 13/10 fr*ckin frightening #BarkWeek
16,This is Jim. He found a fren. Taught him how to sit like the good boys. 12/10 for both https://t.co/chxruIOUJN,This is Jim. He found a fren. Taught him how to sit like the good boys. 12/10 for both
17,This is Zeke. He has a new stick. Very proud of it. Would like you to throw it for him without taking it. 13/10 would do my best https://t.co/HTQ77yNQ5K,This is Zeke. He has a new stick. Very proud of it. Would like you to throw it for him without taking it. 13/10 would do my best
18,This is Ralphus. He's powering up. Attempting maximum borkdrive. 13/10 inspirational af https://t.co/YnYAFCTTiK,This is Ralphus. He's powering up. Attempting maximum borkdrive. 13/10 inspirational af
20,This is Gerald. He was just told he didn't get the job he interviewed for. A h*ckin injustice. 12/10 didn't want the job anyway https://t.co/DK7iDPfuRX,This is Gerald. He was just told he didn't get the job he interviewed for. A h*ckin injustice. 12/10 didn't want the job anyway
21,This is Jeffrey. He has a monopoly on the pool noodles. Currently running a 'boop for two' midweek sale. 13/10 h*ckin strategic https://t.co/PhrUk20Q64,This is Jeffrey. He has a monopoly on the pool noodles. Currently running a 'boop for two' midweek sale. 13/10 h*ckin strategic
22,I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: roxy.thedoxy) https://t.co/20VrLAA8ba,I've yet to rate a Venezuelan Hover Wiener. This is such an honor. 14/10 paw-inspiring af (IG: roxy.thedoxy)
23,This is Canela. She attempted some fancy porch pics. They were unsuccessful. 13/10 someone help her https://t.co/cLyzpcUcMX,This is Canela. She attempted some fancy porch pics. They were unsuccessful. 13/10 someone help her
24,You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo) https://t.co/WZqNqygEyV,You may not have known you needed to see this today. 13/10 please enjoy (IG: emmylouroo)
25,This... is a Jubilant Antarctic House Bear. We only rate dogs. Please only send dogs. Thank you... 12/10 would suffocate in floof https://t.co/4Ad1jzJSdp,This... is a Jubilant Antarctic House Bear. We only rate dogs. Please only send dogs. Thank you... 12/10 would suffocate in floof
26,This is Maya. She's very shy. Rarely leaves her cup. 13/10 would find her an environment to thrive in https://t.co/I6oNy0CgiT,This is Maya. She's very shy. Rarely leaves her cup. 13/10 would find her an environment to thrive in
27,"This is Mingus. He's a wonderful father to his smol pup. Confirmed 13/10, but he needs your help\n\nhttps://t.co/bVi0Yr4Cff https://t.co/ISvKOSkd5b","This is Mingus. He's a wonderful father to his smol pup. Confirmed 13/10, but he needs your help\n"
28,This is Derek. He's late for a dog meeting. 13/10 pet...al to the metal https://t.co/BCoWue0abA,This is Derek. He's late for a dog meeting. 13/10 pet...al to the metal
29,This is Roscoe. Another pupper fallen victim to spontaneous tongue ejections. Get the BlepiPen immediate. 12/10 deep breaths Roscoe https://t.co/RGE08MIJox,This is Roscoe. Another pupper fallen victim to spontaneous tongue ejections. Get the BlepiPen immediate. 12/10 deep breaths Roscoe
31,This is Waffles. His doggles are pupside down. Unsure how to fix. 13/10 someone assist Waffles https://t.co/xZDA9Qsq1O,This is Waffles. His doggles are pupside down. Unsure how to fix. 13/10 someone assist Waffles
...,...,...
2325,This is Walter. He is an Alaskan Terrapin. Loves outdated bandanas. One ear still working. Cool house plant. 10/10 https://t.co/qXpcwENTvn,This is Walter. He is an Alaskan Terrapin. Loves outdated bandanas. One ear still working. Cool house plant. 10/10
2326,This is quite the dog. Gets really excited when not in water. Not very soft tho. Bad at fetch. Can't do tricks. 2/10 https://t.co/aMCTNWO94t,This is quite the dog. Gets really excited when not in water. Not very soft tho. Bad at fetch. Can't do tricks. 2/10
2327,This is a southern Vesuvius bumblegruff. Can drive a truck (wow). Made friends with 5 other nifty dogs (neat). 7/10 https://t.co/LopTBkKa8h,This is a southern Vesuvius bumblegruff. Can drive a truck (wow). Made friends with 5 other nifty dogs (neat). 7/10
2328,Oh goodness. A super rare northeast Qdoba kangaroo mix. Massive feet. No pouch (disappointing). Seems alert. 9/10 https://t.co/Dc7b0E8qFE,Oh goodness. A super rare northeast Qdoba kangaroo mix. Massive feet. No pouch (disappointing). Seems alert. 9/10
2329,Those are sunglasses and a jean jacket. 11/10 dog cool af https://t.co/uHXrPkUEyl,Those are sunglasses and a jean jacket. 11/10 dog cool af
2330,Unique dog here. Very small. Lives in container of Frosted Flakes (?). Short legs. Must be rare 6/10 would still pet https://t.co/XMD9CwjEnM,Unique dog here. Very small. Lives in container of Frosted Flakes (?). Short legs. Must be rare 6/10 would still pet
2331,Here we have a mixed Asiago from the Galápagos Islands. Only one ear working. Big fan of marijuana carpet. 8/10 https://t.co/tltQ5w9aUO,Here we have a mixed Asiago from the Galápagos Islands. Only one ear working. Big fan of marijuana carpet. 8/10
2332,Look at this jokester thinking seat belt laws don't apply to him. Great tongue tho 10/10 https://t.co/VFKG1vxGjB,Look at this jokester thinking seat belt laws don't apply to him. Great tongue tho 10/10
2333,This is an extremely rare horned Parthenon. Not amused. Wears shoes. Overall very nice. 9/10 would pet aggressively https://t.co/QpRjllzWAL,This is an extremely rare horned Parthenon. Not amused. Wears shoes. Overall very nice. 9/10 would pet aggressively
2334,This is a funny dog. Weird toes. Won't come down. Loves branch. Refuses to eat his food. Hard to cuddle with. 3/10 https://t.co/IIXis0zta0,This is a funny dog. Weird toes. Won't come down. Loves branch. Refuses to eat his food. Hard to cuddle with. 3/10
2336,Can take selfies 11/10 https://t.co/ws2AMaNwPW,Can take selfies 11/10
2337,Very concerned about fellow dog trapped in computer. 10/10 https://t.co/0yxApIikpk,Very concerned about fellow dog trapped in computer. 10/10
2338,Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10 https://t.co/Asgdc6kuLX,Not familiar with this breed. No tail (weird). Only 2 legs. Doesn't bark. Surprisingly quick. Shits eggs. 1/10
2339,Oh my. Here you are seeing an Adobe Setter giving birth to twins!!! The world is an amazing place. 11/10 https://t.co/11LvqN4WLq,Oh my. Here you are seeing an Adobe Setter giving birth to twins!!! The world is an amazing place. 11/10
2340,Can stand on stump for what seems like a while. Built that birdhouse? Impressive. Made friends with a squirrel. 8/10 https://t.co/Ri4nMTLq5C,Can stand on stump for what seems like a while. Built that birdhouse? Impressive. Made friends with a squirrel. 8/10
2341,This appears to be a Mongolian Presbyterian mix. Very tired. Tongue slip confirmed. 9/10 would lie down with https://t.co/mnioXo3IfP,This appears to be a Mongolian Presbyterian mix. Very tired. Tongue slip confirmed. 9/10 would lie down with
2342,Here we have a well-established sunblockerspaniel. Lost his other flip-flop. 6/10 not very waterproof https://t.co/3RU6x0vHB7,Here we have a well-established sunblockerspaniel. Lost his other flip-flop. 6/10 not very waterproof
2343,Let's hope this flight isn't Malaysian (lol). What a dog! Almost completely camouflaged. 10/10 I trust this pilot https://t.co/Yk6GHE9tOY,Let's hope this flight isn't Malaysian (lol). What a dog! Almost completely camouflaged. 10/10 I trust this pilot
2344,Here we have a northern speckled Rhododendron. Much sass. Gives 0 fucks. Good tongue. 9/10 would caress sensually https://t.co/ZoL8kq2XFx,Here we have a northern speckled Rhododendron. Much sass. Gives 0 fucks. Good tongue. 9/10 would caress sensually
2345,This is the happiest dog you will ever see. Very committed owner. Nice couch. 10/10 https://t.co/RhUEAloehK,This is the happiest dog you will ever see. Very committed owner. Nice couch. 10/10
2346,Here is the Rand Paul of retrievers folks! He's probably good at poker. Can drink beer (lol rad). 8/10 good dog https://t.co/pYAJkAe76p,Here is the Rand Paul of retrievers folks! He's probably good at poker. Can drink beer (lol rad). 8/10 good dog
2347,My oh my. This is a rare blond Canadian terrier on wheels. Only $8.98. Rather docile. 9/10 very rare https://t.co/yWBqbrzy8O,My oh my. This is a rare blond Canadian terrier on wheels. Only $8.98. Rather docile. 9/10 very rare
2348,Here is a Siberian heavily armored polar bear mix. Strong owner. 10/10 I would do unspeakable things to pet this dog https://t.co/rdivxLiqEt,Here is a Siberian heavily armored polar bear mix. Strong owner. 10/10 I would do unspeakable things to pet this dog
2349,This is an odd dog. Hard on the outside but loving on the inside. Petting still fun. Doesn't play catch well. 2/10 https://t.co/v5A4vzSDdc,This is an odd dog. Hard on the outside but loving on the inside. Petting still fun. Doesn't play catch well. 2/10
2350,This is a truly beautiful English Wilson Staff retriever. Has a nice phone. Privileged. 10/10 would trade lives with https://t.co/fvIbQfHjIe,This is a truly beautiful English Wilson Staff retriever. Has a nice phone. Privileged. 10/10 would trade lives with
2351,Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10 https://t.co/4B7cOc1EDq,Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10
2352,This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unplug the iron. 6/10 https://t.co/DWnyCjf2mx,This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unplug the iron. 6/10
2353,Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af https://t.co/y671yMhoiR,Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af
2354,This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of https://t.co/r7mOb2m0UI,This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of
2355,Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj,Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet

In [98]:
# Copying the 'new_text' column to the old one:
twitter_archive_clean['text'] = create_a_list_of_str_up_to_word(twitter_archive_clean, 'text', 'https')
twitter_archive_clean = twitter_archive_clean.drop(['new_text'], axis=1)

Test

In [99]:
twitter_archive_clean.sample(5)

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
663,790946055508652032,2016-10-25 16:00:09 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Betty. She's assisting with the dishes. Such a good puppo. 12/10 h*ckin helpful af,https://twitter.com/dog_rates/status/790946055508652032/photo/1,12,10,Betty,None,None,None,puppo
459,817827839487737858,2017-01-07 20:18:46 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Buddy. He ran into a glass door once. Now he's h*ckin skeptical. 13/10 empowering af (vid by Brittany Gaunt),https://twitter.com/dog_rates/status/817827839487737858/video/1,13,10,Buddy,None,None,None,None
1539,689661964914655233,2016-01-20 04:13:20 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Meet Luca. He's a Butternut Scooperfloof. Glorious tongue. 12/10 would pet really well,https://twitter.com/dog_rates/status/689661964914655233/photo/1,12,10,Luca,None,None,None,None
2088,670792680469889025,2015-11-29 02:33:32 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Antony. He's a Sheraton Tetrahedron. Skips awkwardly. Doesn't look when he crosses the road (reckless). 7/10,https://twitter.com/dog_rates/status/670792680469889025/photo/1,7,10,Antony,None,None,None,None
43,884162670584377345,2017-07-09 21:29:42 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Meet Yogi. He doesn't have any important dog meetings today he just enjoys looking his best at all times. 12/10 for dangerously dapper doggo,https://twitter.com/dog_rates/status/884162670584377345/photo/1,12,10,Yogi,doggo,None,None,None

image_predictions table

Erroneous datatype for tweet_id.

Define

Convert 'tweed_id' column to string dataype.

Code

In [100]:
image_predictions_clean['tweet_id'] = image_predictions_clean['tweet_id'].astype('str')

Test

In [101]:
image_predictions_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null object
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(1), object(5)
memory usage: 152.1+ KB

Lowercase dog breed names

Define

Capitalize all words found in columns 'p1', 'p2' and 'p3'.

Code

In [102]:
image_predictions_clean['p1'] = image_predictions_clean['p2'].str.title()
image_predictions_clean['p2'] = image_predictions_clean['p2'].str.title()
image_predictions_clean['p3'] = image_predictions_clean['p3'].str.title()

Test

In [103]:
image_predictions_clean.loc[:,['p1', 'p2', 'p3']].sample(10)

                   p1               p2                  p3
1760  Shopping_Basket  Shopping_Basket           Mousetrap
1237       Guinea_Pig       Guinea_Pig            Cardigan
656        Eskimo_Dog       Eskimo_Dog            Malamute
1970   French_Bulldog   French_Bulldog             Printer
192       Toy_Terrier      Toy_Terrier  Miniature_Pinscher
253             Tabby            Tabby        Egyptian_Cat
860          Pembroke         Pembroke             Basenji
1975         Envelope         Envelope         Book_Jacket
1949              Pug              Pug               Boxer
364           Warthog          Warthog       Water_Buffalo

Non-descriptive column names for several variables.

Define

Change the title of non-descriptive columns to more appropriate ones

Code

In [104]:
image_predictions_clean = image_predictions_clean.rename(columns={'jpg_url': 'image_url',
                                                                  'img_num': 'image_number',
                                                                 'p1': 'top_prediction',
                                                                  'p1_conf': 'top_pred_conf',
                                                                  'p2': 'second_prediction',
                                                                  'p2_conf': 'second_pred_conf',
                                                                  'p3': 'third_prediction',
                                                                  'p3_conf': 'third_pred_conf',
                                                                  'p1_dog': 'is_dog_top_pred',
                                                                  'p2_dog': 'is_dog_sec_pred',
                                                                  'p3_dog': 'is_dog_third_pred',
                                                                 })

Test

In [105]:
image_predictions_clean.head()

,tweet_id,image_url,image_number,top_prediction,top_pred_conf,is_dog_top_pred,second_prediction,second_pred_conf,is_dog_sec_pred,third_prediction,third_pred_conf,is_dog_third_pred
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Collie,0.465074,True,Collie,0.156665,True,Shetland_Sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,Miniature_Pinscher,0.506826,True,Miniature_Pinscher,0.074192,True,Rhodesian_Ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,Malinois,0.596461,True,Malinois,0.138584,True,Bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Redbone,0.408143,True,Redbone,0.360687,True,Miniature_Pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,Rottweiler,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

Tidiness issues

twitter_archive table

The expanded_urls column contain in some cells multiple urls that should be cleaned.

Define

Delete all urls and merge the url column of the tweet_json table to twitter_archive_table.

Code

In [106]:
twitter_archive_clean = twitter_archive_clean.drop('expanded_urls',axis=1)
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 2355
Data columns (total 11 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
dtypes: int64(2), object(9)
memory usage: 184.4+ KB

In [107]:
twitter_archive_clean = pd.merge(twitter_archive_clean, tweet_json_clean.loc[:, ['tweet_id','url']], 
                                  on='tweet_id', how='left')
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 12 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
source                1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
doggo                 1967 non-null object
floofer               1967 non-null object
pupper                1967 non-null object
puppo                 1967 non-null object
url                   0 non-null object
dtypes: int64(2), object(10)
memory usage: 199.8+ KB

In [108]:
twitter_archive_clean.tail()

,tweet_id,timestamp,source,text,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,url
1962,666049248165822465,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a 1949 1st generation vulpix. Enjoys sweat tea and Fox News. Cannot be phased. 5/10,5,10,None,None,None,None,None,NaN
1963,666044226329800704,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is a purebred Piers Morgan. Loves to Netflix and chill. Always looks like he forgot to unplug the iron. 6/10,6,10,a,None,None,None,None,NaN
1964,666033412701032449,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here is a very happy pup. Big fan of well-maintained decks. Just look at that tongue. 9/10 would cuddle af,9,10,a,None,None,None,None,NaN
1965,666029285002620928,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is a western brown Mitsubishi terrier. Upset about leaf. Actually 2 dogs here. 7/10 would walk the shit out of,7,10,a,None,None,None,None,NaN
1966,666020888022790149,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet,8,10,None,None,None,None,None,NaN

In [109]:
# If we open the urls and check the text column we can see that we have correctly matched 
# the tweets with the appropriate urls. But if a tweet contains in it's text a url, 
# the url column would contain two https addresses which is clearly not what we want.
# So we will create a column that count https: 
twitter_archive_clean['count_https'] = twitter_archive_clean.url.str.count(r'https')

In [110]:
# So if a tweet has more than one http it must be cleaned:
twitter_archive_clean['count_https'].value_counts()

Series([], Name: count_https, dtype: int64)

In [111]:
# And lets print these tweets: # And le 
twitter_archive_clean[twitter_archive_clean['count_https'] == 2]

Empty DataFrame
Columns: [tweet_id, timestamp, source, text, rating_numerator, rating_denominator, name, doggo, floofer, pupper, puppo, url, count_https]
Index: []

In [112]:
# Two tweets with extra https.
# Remove first https because each tweet 
# url is always at the end of the twitter text
# This function finds the start-end index of a string in a pandas cell.
# It returns multiple indexes if the string is found more than once.
def start_end_index_of_string(dataframe, column, index, string):
    find_index_of_https = [(i.start(), i.end()) for i in re.finditer(
        string, dataframe.loc[index, column])]
    return find_index_of_https

In [113]:
# This function keeps only the last occurence of a selected
# string in a pandas cell and drops everything before it.
def keep_only_last_str_occurence(dataframe, column, index, string):
    my_cell = dataframe.loc[index, column]
    save_my_index = start_end_index_of_string(dataframe, column, index, string)   
    if len(save_my_index) > 1:
        dataframe.at[index, column] = my_cell[save_my_index[-1][0]:]
    else:
        pass

In [114]:
# Search which tweets has more one https in their ulr column 
# and save their index into a list:
index_of_tweets_with_more_than_one_url = twitter_archive_clean[
    twitter_archive_clean['count_https'] == 2].index

In [115]:
# Updating the  cells:
for my_index in index_of_tweets_with_more_than_one_url:
    keep_only_last_str_occurence(twitter_archive_clean, 'url', my_index, 'https')

In [116]:
# Checking the dataset for results
twitter_archive_clean[twitter_archive_clean['count_https'] == 2]

Empty DataFrame
Columns: [tweet_id, timestamp, source, text, rating_numerator, rating_denominator, name, doggo, floofer, pupper, puppo, url, count_https]
Index: []

Test

In [117]:
# Recounting https: 
twitter_archive_clean['count_https'] = twitter_archive_clean.url.str.count(r'https')
twitter_archive_clean['count_https'].value_counts()

Series([], Name: count_https, dtype: int64)

In [118]:
# Dropping the count_https column 
twitter_archive_clean = twitter_archive_clean.drop('count_https', axis=1)

In [119]:
twitter_archive_clean.loc[:, ['text', 'url']].sample(10)

,text,url
420,This is Loki. He'll do your taxes for you. Can also make room in your budget for all the things you bought today. 12/10 what a puppo,NaN
1561,When you realize it doesn't matter how hard you study. You're still going to fail. 10/10,NaN
978,Meet Karma. She's just a head. Lost body during the Second Punic War (unfortunate). Loves to travel 10/10 petable af,NaN
96,"This is Dewey (pronounced ""covfefe""). He's having a good walk. Arguably the best walk. 13/10 would snug softly",NaN
1313,aahhhhkslaldhwnxmzbbs 12/10 for being da smooshiest,NaN
1528,Everyone please just appreciate how perfect these two photos are. 12/10 for both,NaN
1305,This is Griffin. He's desperate for both a physical and emotion connection. 11/10 I'd hug the hell out of Griffin,NaN
114,This is Meatball. He doing what's known in the industry as a mid-strut mlem. H*ckin fancy boy. 12/10 I'd do anything for Meatball,NaN
1234,With great pupper comes great responsibility. 12/10,NaN
1185,I present to you... Dog Jesus. 13/10 (he could be sitting on a rock but I doubt it),NaN

Source column data contains html code that should be cleaned.

Define

Clean the 'source column' using the tweet_json_clean 'source' column.

Code

In [120]:
twitter_archive_clean = pd.merge(twitter_archive_clean, tweet_json_clean.loc[:, ['tweet_id','source']], 
                                  on='tweet_id', how='left')

In [121]:
twitter_archive_clean.head(5)

,tweet_id,timestamp,source_x,text,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,url,source_y
0,892420643555336193,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10,13,10,Phineas,None,None,None,None,NaN,NaN
1,892177421306343426,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10",13,10,Tilly,None,None,None,None,NaN,NaN
2,891815181378084864,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10,12,10,Archie,None,None,None,None,NaN,NaN
3,891689557279858688,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>",This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us,13,10,Darla,None,None,None,None,NaN,NaN
4,891327558926688256,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" rel=""nofollow"">Twitter for iPhone</a>","This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek",12,10,Franklin,None,None,None,None,NaN,NaN

In [122]:
twitter_archive_clean['source_x'].value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     1930
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       26
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source_x, dtype: int64

In [123]:
twitter_archive_clean['source_y'].value_counts()

Series([], Name: source_y, dtype: int64)

In [124]:
twitter_archive_clean[twitter_archive_clean['source_y'] == 'TweetDeck'].loc[:, ['source_x', 'source_y']]

Empty DataFrame
Columns: [source_x, source_y]
Index: []

In [125]:
twitter_archive_clean[twitter_archive_clean['source_y'] == 'Twitter Web Client'].loc[:, ['source_x', 'source_y']]

Empty DataFrame
Columns: [source_x, source_y]
Index: []

In [126]:
# So now let's drop the initial source column, keep the new one and renaming it
twitter_archive_clean = twitter_archive_clean.drop(['source_x'], axis=1)
twitter_archive_clean = twitter_archive_clean.rename(columns={'source_y': 'source'})

Test

In [127]:
twitter_archive_clean.sample(5)

,tweet_id,timestamp,text,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,url,source
534,780931614150983680,2016-09-28 00:46:20 +0000,I want to finally rate this iconic puppo who thinks the parade is all for him. 13/10 would absolutely attend,13,10,None,None,None,None,puppo,NaN,NaN
1627,672488522314567680,2015-12-03 18:52:12 +0000,"This is Jackie. She was all ready to go out, but her friends just cancelled on her. 10/10 hang in there Jackie",10,10,Jackie,None,None,None,None,NaN,NaN
83,872620804844003328,2017-06-08 01:06:27 +0000,This is Monkey. She's supporting owners everywhere with her fancy #PrideMonth bandana. 13/10 love is love is love...,13,10,Monkey,None,None,None,None,NaN,NaN
1484,675781562965868544,2015-12-12 20:57:34 +0000,Say hello to Buddah. He was Waldo for Halloween. 11/10,11,10,Buddah,None,None,None,None,NaN,NaN
709,750868782890057730,2016-07-07 01:47:22 +0000,Meet Milo. He hauled ass until he ran out of treadmill and then passed out from exhaustion. 11/10 sleep tight pupper,11,10,Milo,None,None,pupper,None,NaN,NaN

Four variables (doggo, floofer, pupper, puppo) should be merged in one column

Define

Merge data of 'doggo', 'floofer', 'pupper', 'puppo' in one column.

Code

In [128]:
twitter_archive_clean['doggo'].replace('None', '', inplace=True)
twitter_archive_clean['floofer'].replace('None', '', inplace=True)
twitter_archive_clean['pupper'].replace('None', '', inplace=True)
twitter_archive_clean['puppo'].replace('None', '', inplace=True)

In [129]:
twitter_archive_clean['stage'] = (twitter_archive_clean['doggo'] + 
                                    twitter_archive_clean['floofer'] + 
                                    twitter_archive_clean['pupper'] + 
                                    twitter_archive_clean['puppo'])

In [130]:
twitter_archive_clean['stage'].replace('', 'unidentified', inplace=True)

In [131]:
twitter_archive_clean = twitter_archive_clean.drop(['doggo', 'floofer', 'pupper', 'puppo'], axis=1)

Test

In [132]:
# It seems that 11 dogs are identified belonging in two 'stages':
twitter_archive_clean['stage'].value_counts()

unidentified    1663
pupper           201
doggo             63
puppo             22
doggopupper        9
floofer            7
doggopuppo         1
doggofloofer       1
Name: stage, dtype: int64

In [133]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 9 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
dtypes: int64(2), object(7)
memory usage: 153.7+ KB

In [134]:
twitter_archive_clean.head()

,tweet_id,timestamp,text,rating_numerator,rating_denominator,name,url,source,stage
0,892420643555336193,2017-08-01 16:23:56 +0000,This is Phineas. He's a mystical boy. Only ever appears in the hole of a donut. 13/10,13,10,Phineas,NaN,NaN,unidentified
1,892177421306343426,2017-08-01 00:17:27 +0000,"This is Tilly. She's just checking pup on you. Hopes you're doing ok. If not, she's available for pats, snugs, boops, the whole bit. 13/10",13,10,Tilly,NaN,NaN,unidentified
2,891815181378084864,2017-07-31 00:18:03 +0000,This is Archie. He is a rare Norwegian Pouncing Corgo. Lives in the tall grass. You never know when one may strike. 12/10,12,10,Archie,NaN,NaN,unidentified
3,891689557279858688,2017-07-30 15:58:51 +0000,This is Darla. She commenced a snooze mid meal. 13/10 happens to the best of us,13,10,Darla,NaN,NaN,unidentified
4,891327558926688256,2017-07-29 16:00:24 +0000,"This is Franklin. He would like you to stop calling him ""cute."" He is a very fierce shark and should be respected as such. 12/10 #BarkWeek",12,10,Franklin,NaN,NaN,unidentified

Timestamp should be split into date and time

Define

Convert the 'timestamp' to datetime dataype and split it to date, time, and day of week.

Code

In [135]:
twitter_archive_clean['timestamp'] = pd.DatetimeIndex(twitter_archive_clean['timestamp'])

In [136]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 9 columns):
tweet_id              1967 non-null object
timestamp             1967 non-null datetime64[ns]
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 153.7+ KB

In [137]:
temp = pd.DatetimeIndex(twitter_archive_clean['timestamp'])
twitter_archive_clean['Date'] = temp.date
twitter_archive_clean['Year'] = temp.year
twitter_archive_clean['Month'] = temp.month

In [138]:
twitter_archive_clean['Month'].replace(1, 'January', inplace=True)
twitter_archive_clean['Month'].replace(2, 'February', inplace=True)
twitter_archive_clean['Month'].replace(3, 'March', inplace=True)
twitter_archive_clean['Month'].replace(4, 'April', inplace=True)
twitter_archive_clean['Month'].replace(5, 'May', inplace=True)
twitter_archive_clean['Month'].replace(6, 'June', inplace=True)
twitter_archive_clean['Month'].replace(7, 'July', inplace=True)
twitter_archive_clean['Month'].replace(8, 'August', inplace=True)
twitter_archive_clean['Month'].replace(9, 'September', inplace=True)
twitter_archive_clean['Month'].replace(10, 'October', inplace=True)
twitter_archive_clean['Month'].replace(11, 'November', inplace=True)
twitter_archive_clean['Month'].replace(12, 'December', inplace=True)

In [139]:
twitter_archive_clean['Day_of_Week'] = temp.dayofweek
twitter_archive_clean['Day_of_Week'].replace(0, 'Monday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(1, 'Tuesday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(2, 'Wednesday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(3, 'Thursday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(4, 'Friday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(5, 'Saturday', inplace=True)
twitter_archive_clean['Day_of_Week'].replace(6, 'Sunday', inplace=True)

twitter_archive_clean['Time'] = temp.time

twitter_archive_clean['Hour'] = temp.hour

twitter_archive_clean = twitter_archive_clean.drop('timestamp', axis=1)

Test

In [140]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 14 columns):
tweet_id              1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
Date                  1967 non-null object
Year                  1967 non-null int64
Month                 1967 non-null object
Day_of_Week           1967 non-null object
Time                  1967 non-null object
Hour                  1967 non-null int64
dtypes: int64(4), object(10)
memory usage: 230.5+ KB

In [141]:
twitter_archive_clean.sample(5)

,tweet_id,text,rating_numerator,rating_denominator,name,url,source,stage,Date,Year,Month,Day_of_Week,Time,Hour
1270,685325112850124800,"""Tristan do not speak to me with that kind of tone or I will take away the Xbox."" 10/10",10,10,None,NaN,NaN,unidentified,2016-01-08,2016,January,Friday,05:00:14,5
499,787717603741622272,This is Tonks. She is a service puppo. Can hear a caterpillar hiccup from 7 miles away. 13/10 would follow anywhere,13,10,Tonks,NaN,NaN,puppo,2016-10-16,2016,October,Sunday,18:11:26,18
1118,697881462549430272,This is Carter. He wakes up in the morning and pisses excellence. 10/10 best there is plain and simple,10,10,Carter,NaN,NaN,unidentified,2016-02-11,2016,February,Thursday,20:34:41,20
14,889531135344209921,This is Stuart. He's sporting his favorite fanny pack. Secretly filled with bones only. 13/10 puppared puppo #BarkWeek,13,10,Stuart,NaN,NaN,puppo,2017-07-24,2017,July,Monday,17:02:04,17
203,842163532590374912,Meet George. He looks slightly deflated but overall quite powerful. Not sure how that human restrained him. 12/10 would snug with permission,12,10,George,NaN,NaN,unidentified,2017-03-16,2017,March,Thursday,00:00:07,0

Missing columns: favorite_count and retweet_count

Define

Merge the 'favorite_count' and 'retweet_count' columns of tweet_jso_clean table to the twitter_archive_clean table.

Code

In [142]:
twitter_archive_clean = pd.merge(twitter_archive_clean, 
                                 tweet_json_clean.loc[:, ['tweet_id', 
                                'favorite_count','retweet_count']], 
                                  on='tweet_id', how='left')

Test

In [143]:
twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 16 columns):
tweet_id              1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
Date                  1967 non-null object
Year                  1967 non-null int64
Month                 1967 non-null object
Day_of_Week           1967 non-null object
Time                  1967 non-null object
Hour                  1967 non-null int64
favorite_count        0 non-null float64
retweet_count         0 non-null float64
dtypes: float64(2), int64(4), object(10)
memory usage: 261.2+ KB

In [144]:
twitter_archive_clean.sample(5)

,tweet_id,text,rating_numerator,rating_denominator,name,url,source,stage,Date,Year,Month,Day_of_Week,Time,Hour,favorite_count,retweet_count
1782,669567591774625800,Meet Kollin. He's a Parakeetian Badminton from Denmark. Great artist. Taking break from research. Loves wicker 9/10,9,10,Kollin,NaN,NaN,unidentified,2015-11-25,2015,November,Wednesday,17:25:28,17,NaN,NaN
1600,673213039743795200,This is Dexter. He just got some big news. 10/10,10,10,Dexter,NaN,NaN,unidentified,2015-12-05,2015,December,Saturday,18:51:11,18,NaN,NaN
997,708109389455101952,This is Remington. He was caught off guard by the magical floating cheese. Spooked af. 10/10 deep breaths pup,10,10,Remington,NaN,NaN,unidentified,2016-03-11,2016,March,Friday,01:56:49,1,NaN,NaN
475,792394556390137856,Meet BeBe. She rocks the messy bun of your dreams. H*ckin flawless. 12/10 would watch her tutorial,12,10,BeBe,NaN,NaN,unidentified,2016-10-29,2016,October,Saturday,15:55:58,15,NaN,NaN
1487,675707330206547968,We've got ourselves a battle here. Watch out Reggie. 11/10,11,10,None,NaN,NaN,unidentified,2015-12-12,2015,December,Saturday,16:02:36,16,NaN,NaN

Final cleaning step and Storing the data

Now it's time to create the master pandas DataFrame that we are going to store in a csv file. We will merge the twitter_archive_clean and the image_predictions_clean DataFrames into a single one:

In [145]:
twitter_archive_master = pd.merge(twitter_archive_clean, 
                                 image_predictions_clean.loc[:, ['tweet_id','image_url',
                                                                 'image_number', 'top_prediction', 
                                                                 'top_pred_conf', 'is_dog_top_pred', 
                                                                 'second_prediction', 'second_pred_conf',
                                                                 'is_dog_sec_pred', 'third_prediction', 
                                                                 'third_pred_conf', 'is_dog_third_pred']], 
                                  on='tweet_id', how='left')

In [146]:
twitter_archive_master.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1967 entries, 0 to 1966
Data columns (total 27 columns):
tweet_id              1967 non-null object
text                  1967 non-null object
rating_numerator      1967 non-null int64
rating_denominator    1967 non-null int64
name                  1967 non-null object
url                   0 non-null object
source                0 non-null object
stage                 1967 non-null object
Date                  1967 non-null object
Year                  1967 non-null int64
Month                 1967 non-null object
Day_of_Week           1967 non-null object
Time                  1967 non-null object
Hour                  1967 non-null int64
favorite_count        0 non-null float64
retweet_count         0 non-null float64
image_url             1967 non-null object
image_number          1967 non-null int64
top_prediction        1967 non-null object
top_pred_conf         1967 non-null float64
is_dog_top_pred       1967 non-null bool
second_prediction     1967 non-null object
second_pred_conf      1967 non-null float64
is_dog_sec_pred       1967 non-null bool
third_prediction      1967 non-null object
third_pred_conf       1967 non-null float64
is_dog_third_pred     1967 non-null bool
dtypes: bool(3), float64(5), int64(5), object(14)
memory usage: 389.9+ KB

In [147]:
twitter_archive_master.to_csv('twitter_archive_master.csv')

We will also save as csv files the 3 cleaned datasets (twitter_archive_clean, image_predictions_clean, tweet_json_clean) for future reference

In [148]:
twitter_archive_clean.to_csv('twitter_archive_clean.csv')
image_predictions_clean.to_csv('image_predictions_clean.csv')
tweet_json_clean.to_csv('tweet_json_clean.csv')

Data Analysis and Visualizations

Now it's time to use the cleaned master Dataframe to analyse the data and create relevant and interesting visualizations.

In [149]:
print(twitter_archive_master['Date'][-1:][len(twitter_archive_master)-1])
print(twitter_archive_master['Date'][0])
print((twitter_archive_master['Date'][0] - twitter_archive_master['Date'][-1:][1966]).days)

2015-11-15
2017-08-01
625

The dataset covers 625 days from 15 November of 2015 until 1 of August of 2017.

In [150]:
twitter_archive_master.describe()

,rating_numerator,rating_denominator,Year,Hour,favorite_count,retweet_count,image_number,top_pred_conf,second_pred_conf,third_pred_conf
count,1967.000000,1967.000000,1967.000000,1967.000000,0.0,0.0,1967.000000,1967.000000,1.967000e+03,1.967000e+03
mean,12.311134,10.517031,2015.851551,9.753940,NaN,NaN,1.203355,0.593831,1.340996e-01,6.015671e-02
std,41.769700,7.310967,0.699750,8.619246,NaN,NaN,0.561868,0.272192,1.005274e-01,5.066928e-02
min,0.000000,7.000000,2015.000000,0.000000,NaN,NaN,1.000000,0.044333,1.011300e-08,1.740170e-10
25%,10.000000,10.000000,2015.000000,1.000000,NaN,NaN,1.000000,0.360447,5.314460e-02,1.619495e-02
50%,11.000000,10.000000,2016.000000,4.000000,NaN,NaN,1.000000,0.587764,1.174020e-01,4.952370e-02
75%,12.000000,10.000000,2016.000000,18.000000,NaN,NaN,1.000000,0.844583,1.948820e-01,9.153815e-02
max,1776.000000,170.000000,2017.000000,23.000000,NaN,NaN,4.000000,1.000000,4.880140e-01,2.710420e-01

The mean dog rating for the dataset is 12.3.

On average 8,959 twitter users favorite each WeRateDogs original tweet.

The mean retweet count is substantially lower: 2,771.

The most liked tweet was liked by 131,813 users.

The most retweeted tweet was retweeted 78,740 times.

Which were the most common dog ratings?

In [ ]:
twitter_archive_master['rating_numerator'].value_counts()[:10]

The three most common dog ratings (ignoring the denominator) were 12, 10 and 11.

Which was the most common dog name in the dataset?

In [ ]:
twitter_archive_master['name'].value_counts()[:10]

Charlie was the most common dog name with 11 appearences in the dataset, followed by Oliver, Cooper and Lucy (10 times each).

How many original tweets were posted per month?

In [ ]:
twitter_archive_master.groupby(['Month', 'Year'], 
                               sort=False).count().iloc[::-1, 0]

In [ ]:
tweets_per_month = twitter_archive_master.groupby(['Month', 'Year'], 
                               sort=False).count().iloc[::-1, 0]

In [ ]:
fig, ax = plt.subplots()
sns.set_style("white")
tweets_per_month.plot(kind='bar', color='b')
ax.set_title('Number of original tweets per month', fontsize=14, fontweight="bold")
ax.set_ylabel('count', fontsize=12)
ax.set_xlabel('')
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

November and December of 2015 were the most busy months for WeRateDogs twitter account with the number of original posted tweets exceeding 250 and 350 respectively. From April 2016 and onwards no month had more than 100 tweets posted.

In which day of the week WeRateDogs posted most of its original tweets?

In [ ]:
sort_of_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday', 'Saturday']

plotting_days = pd.DataFrame(twitter_archive_master.groupby('Day_of_Week')['tweet_id'].count())

plotting_days.reset_index(inplace=True)
plotting_days = plotting_days.rename(columns={'tweet_id': 'count'})

plotting_days['Day_of_Week'] = plotting_days.Day_of_Week.astype("category")

plotting_days.Day_of_Week.cat.set_categories(sort_of_days, inplace=True)

plotting_days = plotting_days.sort_values('Day_of_Week')

plotting_days

In [ ]:
fig, ax = plt.subplots()
sns.set_style("white")
sns.barplot(x="Day_of_Week", y="count", data=plotting_days, color='g')
ax.set_title('Number of original tweets per day', fontsize=14, fontweight="bold")
ax.set_ylabel('count', fontsize=12)
plt.xticks(rotation='horizontal')
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

It seems that WeRateDogs was more active on Mondays and less active on Saturdays. There is a decreasing trend in the number of tweets posted as we approach the end of the week.

In which hour of the day WeRateDogs posted most of its original tweets?

In [ ]:
twitter_archive_master['Hour'].value_counts()

In [ ]:
fig, ax = plt.subplots()
twitter_archive_master['Hour'].value_counts(sort=False).plot(kind='bar')
ax.set_title('Number of original tweets per time of the day', fontsize=14, fontweight="bold")
ax.set_ylabel('count', fontsize=12)
ax.set_xlabel('Time of the day', fontsize=12)
plt.xticks(rotation='horizontal') 
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)

Most tweets were posted between midnight and 3 a.m. In general the account holder of WeRateDogs seems to be active from 3 p.m. until 5 a.m. every day.

Which was the most used Twitter app to post tweets by WeRateDogs?

In [ ]:
twitter_archive_master['source'].value_counts() / len(twitter_archive_master) * 100

WeRateDogs moderator clearly prefers tweeting from an iPhone (98% of the time)

For how many dogs a dog 'stage' is available?

In [ ]:
twitter_archive_master['stage'].value_counts()/len(twitter_archive_master) * 100

Most dogs don't have a dog 'stage' (84%). More than 1 out of 10 dogs are identified as puppers (usually a younger dog).

For how many dog breed predictions the trained neural net was most confident?

In [ ]:
twitter_archive_master[twitter_archive_master['top_pred_conf'] == 1]

For only one dog prediction the neural net was confident 100% for its accuracy. It predicted that there is no dog in the tweet image, instead a prayer rug is depicted. The algorithm clearly missed the dog and it was probably confused by the puzzle.

Which tweet was the most retweeted one in the dataset?

In [ ]:
twitter_archive_master[twitter_archive_master['retweet_count'] == max(twitter_archive_master['retweet_count'])]

The most retweeted tweet was this one: https://t.co/7wE9LTEXC4 It shows a dog in a pool